-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accelerator_v2_unpack_Pipeline_VITIS_LOOP_211_1_VITIS_LOOP_212_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bgr_stream1_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bgr_stream1_num_data_valid : IN STD_LOGIC_VECTOR (19 downto 0);
    bgr_stream1_fifo_cap : IN STD_LOGIC_VECTOR (19 downto 0);
    bgr_stream1_full_n : IN STD_LOGIC;
    bgr_stream1_write : OUT STD_LOGIC;
    frame_start_out_in_load : IN STD_LOGIC_VECTOR (0 downto 0);
    frame_started_load : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    hdr_stream4_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    hdr_stream4_num_data_valid : IN STD_LOGIC_VECTOR (16 downto 0);
    hdr_stream4_fifo_cap : IN STD_LOGIC_VECTOR (16 downto 0);
    hdr_stream4_full_n : IN STD_LOGIC;
    hdr_stream4_write : OUT STD_LOGIC;
    p_02_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_02_out_ap_vld : OUT STD_LOGIC;
    frame_started_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    frame_started_flag_1_out_ap_vld : OUT STD_LOGIC;
    frame_started_new_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    frame_started_new_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of accelerator_v2_unpack_Pipeline_VITIS_LOOP_211_1_VITIS_LOOP_212_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_F000 : STD_LOGIC_VECTOR (15 downto 0) := "1111000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln211_reg_389 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln211_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal hdr_stream4_blk_n : STD_LOGIC;
    signal bgr_stream1_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_02_reg_175 : STD_LOGIC_VECTOR (0 downto 0);
    signal frame_started_flag_1_reg_187 : STD_LOGIC_VECTOR (0 downto 0);
    signal frame_started_loc_1_reg_199 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln216_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln216_reg_393 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal or_ln220_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln220_reg_398 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln220_1_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln220_1_reg_403 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_3_reg_408 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_4_reg_413 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_5_reg_418 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_6_reg_423 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_loop_init : STD_LOGIC;
    signal frame_started_new_1_fu_102 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln220_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_fu_106 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln211_fu_224_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal ap_block_pp0_stage4_01001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal xor_ln216_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln216_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln220_1_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln216_1_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln220_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln216_2_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_234 : BOOLEAN;
    signal ap_condition_241 : BOOLEAN;
    signal ap_condition_247 : BOOLEAN;
    signal ap_condition_252 : BOOLEAN;
    signal ap_condition_257 : BOOLEAN;
    signal ap_condition_453 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component accelerator_v2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component accelerator_v2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    frame_started_flag_1_reg_187_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_453)) then 
                    frame_started_flag_1_reg_187 <= or_ln220_reg_398;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    frame_started_flag_1_reg_187 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    frame_started_loc_1_reg_199_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_453)) then 
                    frame_started_loc_1_reg_199 <= and_ln220_1_reg_403;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    frame_started_loc_1_reg_199 <= frame_started_load;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln211_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_106 <= add_ln211_fu_224_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_106 <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;

    p_02_reg_175_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_453)) then 
                    p_02_reg_175 <= or_ln216_reg_393;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    p_02_reg_175 <= frame_start_out_in_load;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                and_ln220_1_reg_403 <= and_ln220_1_fu_304_p2;
                frame_started_new_1_fu_102 <= and_ln220_fu_298_p2;
                or_ln216_reg_393 <= or_ln216_fu_262_p2;
                or_ln220_reg_398 <= or_ln220_fu_286_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln211_reg_389 <= icmp_ln211_fu_218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_3_reg_408 <= in_stream_TDATA(55 downto 32);
                p_4_reg_413 <= in_stream_TDATA(79 downto 56);
                p_5_reg_418 <= in_stream_TDATA(103 downto 80);
                p_6_reg_423 <= in_stream_TDATA(127 downto 104);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage4_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln211_fu_224_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv16_1));
    and_ln216_fu_256_p2 <= (xor_ln216_fu_250_p2 and in_stream_TUSER);
    and_ln220_1_fu_304_p2 <= (xor_ln220_fu_292_p2 and or_ln216_2_fu_274_p2);
    and_ln220_fu_298_p2 <= (xor_ln220_fu_292_p2 and or_ln216_1_fu_268_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389, in_stream_TVALID, hdr_stream4_full_n)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0)) or ((hdr_stream4_full_n = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0)) or ((in_stream_TVALID = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0))));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389, in_stream_TVALID, hdr_stream4_full_n)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0)) or ((hdr_stream4_full_n = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0)) or ((in_stream_TVALID = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0))));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389, in_stream_TVALID, hdr_stream4_full_n)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0)) or ((hdr_stream4_full_n = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0)) or ((in_stream_TVALID = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0))));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage2_01001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage2_11001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage2_subdone <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_01001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage3_01001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage3_11001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage3_subdone <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_01001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage4_01001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage4_11001 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_pp0_stage4_subdone <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage1_iter0_assign_proc : process(bgr_stream1_full_n, icmp_ln211_reg_389, in_stream_TVALID, hdr_stream4_full_n)
    begin
                ap_block_state2_pp0_stage1_iter0 <= (((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0)) or ((hdr_stream4_full_n = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0)) or ((in_stream_TVALID = ap_const_logic_0) and (icmp_ln211_reg_389 = ap_const_lv1_0)));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0));
    end process;


    ap_block_state6_pp0_stage0_iter1_assign_proc : process(bgr_stream1_full_n, icmp_ln211_reg_389)
    begin
                ap_block_state6_pp0_stage0_iter1 <= ((icmp_ln211_reg_389 = ap_const_lv1_0) and (bgr_stream1_full_n = ap_const_logic_0));
    end process;


    ap_condition_234_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_01001)
    begin
                ap_condition_234 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_241_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_01001)
    begin
                ap_condition_241 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_247_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_01001)
    begin
                ap_condition_247 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_252_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_01001)
    begin
                ap_condition_252 <= ((ap_const_boolean_0 = ap_block_pp0_stage4_01001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4));
    end process;


    ap_condition_257_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_257 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_453_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln211_reg_389, ap_block_pp0_stage0_11001)
    begin
                ap_condition_453 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln211_fu_218_p2)
    begin
        if (((icmp_ln211_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_106;
        end if; 
    end process;


    bgr_stream1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, bgr_stream1_full_n, icmp_ln211_reg_389, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_block_pp0_stage4, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            bgr_stream1_blk_n <= bgr_stream1_full_n;
        else 
            bgr_stream1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bgr_stream1_din_assign_proc : process(icmp_ln211_reg_389, in_stream_TDATA, p_3_reg_408, p_4_reg_413, p_5_reg_418, p_6_reg_423, ap_condition_234, ap_condition_241, ap_condition_247, ap_condition_252, ap_condition_257)
    begin
        if ((icmp_ln211_reg_389 = ap_const_lv1_0)) then
            if ((ap_const_boolean_1 = ap_condition_257)) then 
                bgr_stream1_din <= p_6_reg_423;
            elsif ((ap_const_boolean_1 = ap_condition_252)) then 
                bgr_stream1_din <= p_5_reg_418;
            elsif ((ap_const_boolean_1 = ap_condition_247)) then 
                bgr_stream1_din <= p_4_reg_413;
            elsif ((ap_const_boolean_1 = ap_condition_241)) then 
                bgr_stream1_din <= p_3_reg_408;
            elsif ((ap_const_boolean_1 = ap_condition_234)) then 
                bgr_stream1_din <= in_stream_TDATA(31 downto 8);
            else 
                bgr_stream1_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            bgr_stream1_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    bgr_stream1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln211_reg_389, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            bgr_stream1_write <= ap_const_logic_1;
        else 
            bgr_stream1_write <= ap_const_logic_0;
        end if; 
    end process;

    frame_started_flag_1_out <= frame_started_flag_1_reg_187;

    frame_started_flag_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln211_fu_218_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln211_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            frame_started_flag_1_out_ap_vld <= ap_const_logic_1;
        else 
            frame_started_flag_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    frame_started_new_1_out <= frame_started_new_1_fu_102;

    frame_started_new_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln211_fu_218_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln211_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            frame_started_new_1_out_ap_vld <= ap_const_logic_1;
        else 
            frame_started_new_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hdr_stream4_blk_n_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln211_reg_389, hdr_stream4_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hdr_stream4_blk_n <= hdr_stream4_full_n;
        else 
            hdr_stream4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    hdr_stream4_din <= in_stream_TDATA(8 - 1 downto 0);

    hdr_stream4_write_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln211_reg_389, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            hdr_stream4_write <= ap_const_logic_1;
        else 
            hdr_stream4_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln211_fu_218_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv16_F000) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln211_reg_389, in_stream_TVALID, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln211_reg_389, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln211_reg_389 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    or_ln216_1_fu_268_p2 <= (frame_started_new_1_fu_102 or and_ln216_fu_256_p2);
    or_ln216_2_fu_274_p2 <= (in_stream_TUSER or frame_started_loc_1_reg_199);
    or_ln216_fu_262_p2 <= (p_02_reg_175 or and_ln216_fu_256_p2);
    or_ln220_1_fu_280_p2 <= (in_stream_TLAST or and_ln216_fu_256_p2);
    or_ln220_fu_286_p2 <= (or_ln220_1_fu_280_p2 or frame_started_flag_1_reg_187);
    p_02_out <= p_02_reg_175;

    p_02_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln211_fu_218_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln211_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_02_out_ap_vld <= ap_const_logic_1;
        else 
            p_02_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln216_fu_250_p2 <= (frame_started_loc_1_reg_199 xor ap_const_lv1_1);
    xor_ln220_fu_292_p2 <= (in_stream_TLAST xor ap_const_lv1_1);
end behav;
