// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_passthrough_xfrgb2gray_7_0_460_640_4_2_2_26_12_18400_Pipeline_columnloop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_in_data47_dout,
        img_in_data47_num_data_valid,
        img_in_data47_fifo_cap,
        img_in_data47_empty_n,
        img_in_data47_read,
        img_gray_data48_din,
        img_gray_data48_num_data_valid,
        img_gray_data48_fifo_cap,
        img_gray_data48_full_n,
        img_gray_data48_write,
        trunc_ln
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] img_in_data47_dout;
input  [1:0] img_in_data47_num_data_valid;
input  [1:0] img_in_data47_fifo_cap;
input   img_in_data47_empty_n;
output   img_in_data47_read;
output  [31:0] img_gray_data48_din;
input  [1:0] img_gray_data48_num_data_valid;
input  [1:0] img_gray_data48_fifo_cap;
input   img_gray_data48_full_n;
output   img_gray_data48_write;
input  [13:0] trunc_ln;

reg ap_idle;
reg img_in_data47_read;
reg img_gray_data48_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln5506_fu_127_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    img_in_data47_blk_n;
wire    ap_block_pp0_stage0;
reg    img_gray_data48_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] p_1_reg_466;
reg   [7:0] p_1_reg_466_pp0_iter2_reg;
reg   [7:0] p_2_reg_471;
reg   [7:0] p_4_reg_476;
reg   [7:0] p_4_reg_476_pp0_iter2_reg;
reg   [7:0] p_5_reg_481;
reg   [7:0] p_7_reg_486;
reg   [7:0] p_7_reg_486_pp0_iter2_reg;
reg   [7:0] p_8_reg_491;
reg   [7:0] p_10_reg_496;
reg   [7:0] p_10_reg_496_pp0_iter2_reg;
reg   [7:0] p_11_reg_501;
wire   [21:0] grp_fu_359_p2;
wire   [21:0] grp_fu_365_p2;
wire   [21:0] grp_fu_371_p2;
wire   [21:0] grp_fu_377_p2;
reg   [13:0] j_V_fu_96;
wire   [13:0] add_ln1027_fu_133_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_j_V_load;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] p_fu_144_p1;
wire   [7:0] p_3_fu_168_p4;
wire   [7:0] p_6_fu_198_p4;
wire   [7:0] p_9_fu_228_p4;
wire   [21:0] grp_fu_383_p3;
wire   [21:0] grp_fu_392_p3;
wire   [21:0] grp_fu_401_p3;
wire   [21:0] grp_fu_410_p3;
wire   [22:0] grp_fu_419_p3;
wire   [22:0] grp_fu_428_p3;
wire   [22:0] grp_fu_437_p3;
wire   [22:0] grp_fu_446_p3;
wire   [7:0] Value_uchar_3_fu_337_p4;
wire   [7:0] Value_uchar_2_fu_328_p4;
wire   [7:0] Value_uchar_1_fu_319_p4;
wire   [7:0] Value_uchar_fu_310_p4;
wire   [7:0] grp_fu_359_p0;
wire   [13:0] grp_fu_359_p1;
wire   [7:0] grp_fu_365_p0;
wire   [13:0] grp_fu_365_p1;
wire   [7:0] grp_fu_371_p0;
wire   [13:0] grp_fu_371_p1;
wire   [7:0] grp_fu_377_p0;
wire   [13:0] grp_fu_377_p1;
wire   [7:0] grp_fu_383_p0;
wire   [11:0] grp_fu_383_p1;
wire   [7:0] grp_fu_392_p0;
wire   [11:0] grp_fu_392_p1;
wire   [7:0] grp_fu_401_p0;
wire   [11:0] grp_fu_401_p1;
wire   [7:0] grp_fu_410_p0;
wire   [11:0] grp_fu_410_p1;
wire   [7:0] grp_fu_419_p0;
wire   [14:0] grp_fu_419_p1;
wire   [21:0] grp_fu_419_p2;
wire   [7:0] grp_fu_428_p0;
wire   [14:0] grp_fu_428_p1;
wire   [21:0] grp_fu_428_p2;
wire   [7:0] grp_fu_437_p0;
wire   [14:0] grp_fu_437_p1;
wire   [21:0] grp_fu_437_p2;
wire   [7:0] grp_fu_446_p0;
wire   [14:0] grp_fu_446_p1;
wire   [21:0] grp_fu_446_p2;
reg    grp_fu_359_ce;
reg    grp_fu_365_ce;
reg    grp_fu_371_ce;
reg    grp_fu_377_ce;
reg    grp_fu_383_ce;
reg    grp_fu_392_ce;
reg    grp_fu_401_ce;
reg    grp_fu_410_ce;
reg    grp_fu_419_ce;
reg    grp_fu_428_ce;
reg    grp_fu_437_ce;
reg    grp_fu_446_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [21:0] grp_fu_359_p00;
wire   [21:0] grp_fu_365_p00;
wire   [21:0] grp_fu_371_p00;
wire   [21:0] grp_fu_377_p00;
wire   [19:0] grp_fu_383_p00;
wire   [19:0] grp_fu_392_p00;
wire   [19:0] grp_fu_401_p00;
wire   [19:0] grp_fu_410_p00;
wire   [22:0] grp_fu_419_p00;
wire   [22:0] grp_fu_419_p20;
wire   [22:0] grp_fu_428_p00;
wire   [22:0] grp_fu_428_p20;
wire   [22:0] grp_fu_437_p00;
wire   [22:0] grp_fu_437_p20;
wire   [22:0] grp_fu_446_p00;
wire   [22:0] grp_fu_446_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

image_passthrough_mul_mul_8ns_14ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
mul_mul_8ns_14ns_22_4_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_359_p0),
    .din1(grp_fu_359_p1),
    .ce(grp_fu_359_ce),
    .dout(grp_fu_359_p2)
);

image_passthrough_mul_mul_8ns_14ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
mul_mul_8ns_14ns_22_4_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_365_p0),
    .din1(grp_fu_365_p1),
    .ce(grp_fu_365_ce),
    .dout(grp_fu_365_p2)
);

image_passthrough_mul_mul_8ns_14ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
mul_mul_8ns_14ns_22_4_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_371_p0),
    .din1(grp_fu_371_p1),
    .ce(grp_fu_371_ce),
    .dout(grp_fu_371_p2)
);

image_passthrough_mul_mul_8ns_14ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 22 ))
mul_mul_8ns_14ns_22_4_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_377_p0),
    .din1(grp_fu_377_p1),
    .ce(grp_fu_377_ce),
    .dout(grp_fu_377_p2)
);

image_passthrough_mac_muladd_8ns_12ns_22ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8ns_12ns_22ns_22_4_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_383_p0),
    .din1(grp_fu_383_p1),
    .din2(grp_fu_359_p2),
    .ce(grp_fu_383_ce),
    .dout(grp_fu_383_p3)
);

image_passthrough_mac_muladd_8ns_12ns_22ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8ns_12ns_22ns_22_4_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_392_p0),
    .din1(grp_fu_392_p1),
    .din2(grp_fu_365_p2),
    .ce(grp_fu_392_ce),
    .dout(grp_fu_392_p3)
);

image_passthrough_mac_muladd_8ns_12ns_22ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8ns_12ns_22ns_22_4_1_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_401_p0),
    .din1(grp_fu_401_p1),
    .din2(grp_fu_371_p2),
    .ce(grp_fu_401_ce),
    .dout(grp_fu_401_p3)
);

image_passthrough_mac_muladd_8ns_12ns_22ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8ns_12ns_22ns_22_4_1_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_410_p0),
    .din1(grp_fu_410_p1),
    .din2(grp_fu_377_p2),
    .ce(grp_fu_410_ce),
    .dout(grp_fu_410_p3)
);

image_passthrough_mac_muladd_8ns_15ns_22ns_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_8ns_15ns_22ns_23_4_1_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_419_p0),
    .din1(grp_fu_419_p1),
    .din2(grp_fu_419_p2),
    .ce(grp_fu_419_ce),
    .dout(grp_fu_419_p3)
);

image_passthrough_mac_muladd_8ns_15ns_22ns_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_8ns_15ns_22ns_23_4_1_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_428_p0),
    .din1(grp_fu_428_p1),
    .din2(grp_fu_428_p2),
    .ce(grp_fu_428_ce),
    .dout(grp_fu_428_p3)
);

image_passthrough_mac_muladd_8ns_15ns_22ns_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_8ns_15ns_22ns_23_4_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_437_p0),
    .din1(grp_fu_437_p1),
    .din2(grp_fu_437_p2),
    .ce(grp_fu_437_ce),
    .dout(grp_fu_437_p3)
);

image_passthrough_mac_muladd_8ns_15ns_22ns_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_8ns_15ns_22ns_23_4_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_446_p0),
    .din1(grp_fu_446_p1),
    .din2(grp_fu_446_p2),
    .ce(grp_fu_446_ce),
    .dout(grp_fu_446_p3)
);

image_passthrough_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln5506_fu_127_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_V_fu_96 <= add_ln1027_fu_133_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_V_fu_96 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        p_10_reg_496 <= {{img_in_data47_dout[87:80]}};
        p_11_reg_501 <= {{img_in_data47_dout[95:88]}};
        p_1_reg_466 <= {{img_in_data47_dout[15:8]}};
        p_2_reg_471 <= {{img_in_data47_dout[23:16]}};
        p_4_reg_476 <= {{img_in_data47_dout[39:32]}};
        p_5_reg_481 <= {{img_in_data47_dout[47:40]}};
        p_7_reg_486 <= {{img_in_data47_dout[63:56]}};
        p_8_reg_491 <= {{img_in_data47_dout[71:64]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        p_10_reg_496_pp0_iter2_reg <= p_10_reg_496;
        p_1_reg_466_pp0_iter2_reg <= p_1_reg_466;
        p_4_reg_476_pp0_iter2_reg <= p_4_reg_476;
        p_7_reg_486_pp0_iter2_reg <= p_7_reg_486;
    end
end

always @ (*) begin
    if (((icmp_ln5506_fu_127_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_V_load = 14'd0;
    end else begin
        ap_sig_allocacmp_j_V_load = j_V_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_359_ce = 1'b1;
    end else begin
        grp_fu_359_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_365_ce = 1'b1;
    end else begin
        grp_fu_365_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_371_ce = 1'b1;
    end else begin
        grp_fu_371_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_377_ce = 1'b1;
    end else begin
        grp_fu_377_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_383_ce = 1'b1;
    end else begin
        grp_fu_383_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_392_ce = 1'b1;
    end else begin
        grp_fu_392_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_401_ce = 1'b1;
    end else begin
        grp_fu_401_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_410_ce = 1'b1;
    end else begin
        grp_fu_410_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_419_ce = 1'b1;
    end else begin
        grp_fu_419_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_428_ce = 1'b1;
    end else begin
        grp_fu_428_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_437_ce = 1'b1;
    end else begin
        grp_fu_437_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_446_ce = 1'b1;
    end else begin
        grp_fu_446_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        img_gray_data48_blk_n = img_gray_data48_full_n;
    end else begin
        img_gray_data48_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        img_gray_data48_write = 1'b1;
    end else begin
        img_gray_data48_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_in_data47_blk_n = img_in_data47_empty_n;
    end else begin
        img_in_data47_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_in_data47_read = 1'b1;
    end else begin
        img_in_data47_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Value_uchar_1_fu_319_p4 = {{grp_fu_428_p3[22:15]}};

assign Value_uchar_2_fu_328_p4 = {{grp_fu_437_p3[22:15]}};

assign Value_uchar_3_fu_337_p4 = {{grp_fu_446_p3[22:15]}};

assign Value_uchar_fu_310_p4 = {{grp_fu_419_p3[22:15]}};

assign add_ln1027_fu_133_p2 = (ap_sig_allocacmp_j_V_load + 14'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((img_gray_data48_full_n == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((img_in_data47_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((img_gray_data48_full_n == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((img_in_data47_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((img_gray_data48_full_n == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((img_in_data47_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (img_in_data47_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = (img_gray_data48_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_359_p0 = grp_fu_359_p00;

assign grp_fu_359_p00 = p_fu_144_p1;

assign grp_fu_359_p1 = 22'd9798;

assign grp_fu_365_p0 = grp_fu_365_p00;

assign grp_fu_365_p00 = p_3_fu_168_p4;

assign grp_fu_365_p1 = 22'd9798;

assign grp_fu_371_p0 = grp_fu_371_p00;

assign grp_fu_371_p00 = p_6_fu_198_p4;

assign grp_fu_371_p1 = 22'd9798;

assign grp_fu_377_p0 = grp_fu_377_p00;

assign grp_fu_377_p00 = p_9_fu_228_p4;

assign grp_fu_377_p1 = 22'd9798;

assign grp_fu_383_p0 = grp_fu_383_p00;

assign grp_fu_383_p00 = p_2_reg_471;

assign grp_fu_383_p1 = 20'd3736;

assign grp_fu_392_p0 = grp_fu_392_p00;

assign grp_fu_392_p00 = p_5_reg_481;

assign grp_fu_392_p1 = 20'd3736;

assign grp_fu_401_p0 = grp_fu_401_p00;

assign grp_fu_401_p00 = p_8_reg_491;

assign grp_fu_401_p1 = 20'd3736;

assign grp_fu_410_p0 = grp_fu_410_p00;

assign grp_fu_410_p00 = p_11_reg_501;

assign grp_fu_410_p1 = 20'd3736;

assign grp_fu_419_p0 = grp_fu_419_p00;

assign grp_fu_419_p00 = p_1_reg_466_pp0_iter2_reg;

assign grp_fu_419_p1 = 23'd19235;

assign grp_fu_419_p2 = grp_fu_419_p20;

assign grp_fu_419_p20 = grp_fu_383_p3;

assign grp_fu_428_p0 = grp_fu_428_p00;

assign grp_fu_428_p00 = p_4_reg_476_pp0_iter2_reg;

assign grp_fu_428_p1 = 23'd19235;

assign grp_fu_428_p2 = grp_fu_428_p20;

assign grp_fu_428_p20 = grp_fu_392_p3;

assign grp_fu_437_p0 = grp_fu_437_p00;

assign grp_fu_437_p00 = p_7_reg_486_pp0_iter2_reg;

assign grp_fu_437_p1 = 23'd19235;

assign grp_fu_437_p2 = grp_fu_437_p20;

assign grp_fu_437_p20 = grp_fu_401_p3;

assign grp_fu_446_p0 = grp_fu_446_p00;

assign grp_fu_446_p00 = p_10_reg_496_pp0_iter2_reg;

assign grp_fu_446_p1 = 23'd19235;

assign grp_fu_446_p2 = grp_fu_446_p20;

assign grp_fu_446_p20 = grp_fu_410_p3;

assign icmp_ln5506_fu_127_p2 = ((ap_sig_allocacmp_j_V_load == trunc_ln) ? 1'b1 : 1'b0);

assign img_gray_data48_din = {{{{Value_uchar_3_fu_337_p4}, {Value_uchar_2_fu_328_p4}}, {Value_uchar_1_fu_319_p4}}, {Value_uchar_fu_310_p4}};

assign p_3_fu_168_p4 = {{img_in_data47_dout[31:24]}};

assign p_6_fu_198_p4 = {{img_in_data47_dout[55:48]}};

assign p_9_fu_228_p4 = {{img_in_data47_dout[79:72]}};

assign p_fu_144_p1 = img_in_data47_dout[7:0];

endmodule //image_passthrough_xfrgb2gray_7_0_460_640_4_2_2_26_12_18400_Pipeline_columnloop
