// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accelerator_v2_xFGaussianFilter5x5_Pipeline_Col_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        gray_mat_data44_dout,
        gray_mat_data44_num_data_valid,
        gray_mat_data44_fifo_cap,
        gray_mat_data44_empty_n,
        gray_mat_data44_read,
        blurred_mat_data45_din,
        blurred_mat_data45_num_data_valid,
        blurred_mat_data45_fifo_cap,
        blurred_mat_data45_full_n,
        blurred_mat_data45_write,
        tp1_V_cast,
        tp2_V_cast,
        mid_V_cast,
        bottom1_V_cast,
        bottom2_V_cast,
        p_read,
        p_read1,
        p_read2,
        row_ind_V_cast,
        buf_V_4_address0,
        buf_V_4_ce0,
        buf_V_4_q0,
        buf_V_4_address1,
        buf_V_4_ce1,
        buf_V_4_we1,
        buf_V_4_d1,
        buf_V_3_address0,
        buf_V_3_ce0,
        buf_V_3_q0,
        buf_V_3_address1,
        buf_V_3_ce1,
        buf_V_3_we1,
        buf_V_3_d1,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_q0,
        buf_V_2_address1,
        buf_V_2_ce1,
        buf_V_2_we1,
        buf_V_2_d1,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_q0,
        buf_V_1_address1,
        buf_V_1_ce1,
        buf_V_1_we1,
        buf_V_1_d1,
        buf_V_address0,
        buf_V_ce0,
        buf_V_q0,
        buf_V_address1,
        buf_V_ce1,
        buf_V_we1,
        buf_V_d1,
        cmp_i_i380_i,
        src_buf5_V_2_out,
        src_buf5_V_2_out_ap_vld,
        src_buf5_V_1_out,
        src_buf5_V_1_out_ap_vld,
        src_buf5_V_out,
        src_buf5_V_out_ap_vld,
        src_buf5_V_0_out,
        src_buf5_V_0_out_ap_vld,
        src_buf4_V_2_out,
        src_buf4_V_2_out_ap_vld,
        src_buf4_V_1_out,
        src_buf4_V_1_out_ap_vld,
        src_buf4_V_out,
        src_buf4_V_out_ap_vld,
        src_buf4_V_0_out,
        src_buf4_V_0_out_ap_vld,
        src_buf3_V_2_out,
        src_buf3_V_2_out_ap_vld,
        src_buf3_V_1_out,
        src_buf3_V_1_out_ap_vld,
        src_buf3_V_out,
        src_buf3_V_out_ap_vld,
        src_buf3_V_0_out,
        src_buf3_V_0_out_ap_vld,
        src_buf2_V_2_out,
        src_buf2_V_2_out_ap_vld,
        src_buf2_V_1_out,
        src_buf2_V_1_out_ap_vld,
        src_buf2_V_out,
        src_buf2_V_out_ap_vld,
        src_buf2_V_0_out,
        src_buf2_V_0_out_ap_vld,
        src_buf1_V_2_out,
        src_buf1_V_2_out_ap_vld,
        src_buf1_V_1_out,
        src_buf1_V_1_out_ap_vld,
        src_buf1_V_out,
        src_buf1_V_out_ap_vld,
        src_buf1_V_0_out,
        src_buf1_V_0_out_ap_vld,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din1,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din2,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din3,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din4,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din5,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din6,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din7,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din8,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din9,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din10,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din11,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din12,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din13,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din14,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din15,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din16,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din17,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din18,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din19,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din20,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din21,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din22,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din23,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din24,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din25,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din26,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din27,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din28,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_dout0,
        grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] gray_mat_data44_dout;
input  [12:0] gray_mat_data44_num_data_valid;
input  [12:0] gray_mat_data44_fifo_cap;
input   gray_mat_data44_empty_n;
output   gray_mat_data44_read;
output  [7:0] blurred_mat_data45_din;
input  [12:0] blurred_mat_data45_num_data_valid;
input  [12:0] blurred_mat_data45_fifo_cap;
input   blurred_mat_data45_full_n;
output   blurred_mat_data45_write;
input  [2:0] tp1_V_cast;
input  [2:0] tp2_V_cast;
input  [2:0] mid_V_cast;
input  [2:0] bottom1_V_cast;
input  [2:0] bottom2_V_cast;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [2:0] row_ind_V_cast;
output  [9:0] buf_V_4_address0;
output   buf_V_4_ce0;
input  [7:0] buf_V_4_q0;
output  [9:0] buf_V_4_address1;
output   buf_V_4_ce1;
output   buf_V_4_we1;
output  [7:0] buf_V_4_d1;
output  [9:0] buf_V_3_address0;
output   buf_V_3_ce0;
input  [7:0] buf_V_3_q0;
output  [9:0] buf_V_3_address1;
output   buf_V_3_ce1;
output   buf_V_3_we1;
output  [7:0] buf_V_3_d1;
output  [9:0] buf_V_2_address0;
output   buf_V_2_ce0;
input  [7:0] buf_V_2_q0;
output  [9:0] buf_V_2_address1;
output   buf_V_2_ce1;
output   buf_V_2_we1;
output  [7:0] buf_V_2_d1;
output  [9:0] buf_V_1_address0;
output   buf_V_1_ce0;
input  [7:0] buf_V_1_q0;
output  [9:0] buf_V_1_address1;
output   buf_V_1_ce1;
output   buf_V_1_we1;
output  [7:0] buf_V_1_d1;
output  [9:0] buf_V_address0;
output   buf_V_ce0;
input  [7:0] buf_V_q0;
output  [9:0] buf_V_address1;
output   buf_V_ce1;
output   buf_V_we1;
output  [7:0] buf_V_d1;
input  [0:0] cmp_i_i380_i;
output  [7:0] src_buf5_V_2_out;
output   src_buf5_V_2_out_ap_vld;
output  [7:0] src_buf5_V_1_out;
output   src_buf5_V_1_out_ap_vld;
output  [7:0] src_buf5_V_out;
output   src_buf5_V_out_ap_vld;
output  [7:0] src_buf5_V_0_out;
output   src_buf5_V_0_out_ap_vld;
output  [7:0] src_buf4_V_2_out;
output   src_buf4_V_2_out_ap_vld;
output  [7:0] src_buf4_V_1_out;
output   src_buf4_V_1_out_ap_vld;
output  [7:0] src_buf4_V_out;
output   src_buf4_V_out_ap_vld;
output  [7:0] src_buf4_V_0_out;
output   src_buf4_V_0_out_ap_vld;
output  [7:0] src_buf3_V_2_out;
output   src_buf3_V_2_out_ap_vld;
output  [7:0] src_buf3_V_1_out;
output   src_buf3_V_1_out_ap_vld;
output  [7:0] src_buf3_V_out;
output   src_buf3_V_out_ap_vld;
output  [7:0] src_buf3_V_0_out;
output   src_buf3_V_0_out_ap_vld;
output  [7:0] src_buf2_V_2_out;
output   src_buf2_V_2_out_ap_vld;
output  [7:0] src_buf2_V_1_out;
output   src_buf2_V_1_out_ap_vld;
output  [7:0] src_buf2_V_out;
output   src_buf2_V_out_ap_vld;
output  [7:0] src_buf2_V_0_out;
output   src_buf2_V_0_out_ap_vld;
output  [7:0] src_buf1_V_2_out;
output   src_buf1_V_2_out_ap_vld;
output  [7:0] src_buf1_V_1_out;
output   src_buf1_V_1_out_ap_vld;
output  [7:0] src_buf1_V_out;
output   src_buf1_V_out_ap_vld;
output  [7:0] src_buf1_V_0_out;
output   src_buf1_V_0_out_ap_vld;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din1;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din2;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din3;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din4;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din5;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din6;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din7;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din8;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din9;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din10;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din11;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din12;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din13;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din14;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din15;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din16;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din17;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din18;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din19;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din20;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din21;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din22;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din23;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din24;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din25;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din26;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din27;
output  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din28;
input  [7:0] grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_dout0;
output   grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_ce;

reg ap_idle;
reg gray_mat_data44_read;
reg blurred_mat_data45_write;
reg buf_V_4_ce0;
reg buf_V_4_ce1;
reg buf_V_4_we1;
reg[7:0] buf_V_4_d1;
reg buf_V_3_ce0;
reg buf_V_3_ce1;
reg buf_V_3_we1;
reg[7:0] buf_V_3_d1;
reg buf_V_2_ce0;
reg buf_V_2_ce1;
reg buf_V_2_we1;
reg[7:0] buf_V_2_d1;
reg buf_V_1_ce0;
reg buf_V_1_ce1;
reg buf_V_1_we1;
reg[7:0] buf_V_1_d1;
reg buf_V_ce0;
reg buf_V_ce1;
reg buf_V_we1;
reg[7:0] buf_V_d1;
reg src_buf5_V_2_out_ap_vld;
reg src_buf5_V_1_out_ap_vld;
reg src_buf5_V_out_ap_vld;
reg src_buf5_V_0_out_ap_vld;
reg src_buf4_V_2_out_ap_vld;
reg src_buf4_V_1_out_ap_vld;
reg src_buf4_V_out_ap_vld;
reg src_buf4_V_0_out_ap_vld;
reg src_buf3_V_2_out_ap_vld;
reg src_buf3_V_1_out_ap_vld;
reg src_buf3_V_out_ap_vld;
reg src_buf3_V_0_out_ap_vld;
reg src_buf2_V_2_out_ap_vld;
reg src_buf2_V_1_out_ap_vld;
reg src_buf2_V_out_ap_vld;
reg src_buf2_V_0_out_ap_vld;
reg src_buf1_V_2_out_ap_vld;
reg src_buf1_V_1_out_ap_vld;
reg src_buf1_V_out_ap_vld;
reg src_buf1_V_0_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln624_reg_1203;
wire   [0:0] cmp_i_i380_i_read_reg_1149;
reg    ap_predicate_op105_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
reg   [0:0] icmp_ln668_reg_1232;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter11_reg;
reg    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln624_fu_677_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gray_mat_data44_blk_n;
wire    ap_block_pp0_stage0;
reg    blurred_mat_data45_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [2:0] row_ind_V_cast_read_reg_1153;
wire   [2:0] bottom2_V_cast_read_reg_1172;
reg   [9:0] col_V_3_reg_1197;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter1_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter2_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter3_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter4_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter5_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter6_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter7_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter8_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter9_reg;
reg   [0:0] icmp_ln624_reg_1203_pp0_iter10_reg;
reg   [9:0] buf_V_addr_reg_1207;
reg   [9:0] buf_V_1_addr_reg_1212;
reg   [9:0] buf_V_2_addr_reg_1217;
reg   [9:0] buf_V_3_addr_reg_1222;
reg   [9:0] buf_V_4_addr_reg_1227;
wire   [0:0] icmp_ln668_fu_711_p2;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter2_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter3_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter4_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter5_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter6_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter7_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter8_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter9_reg;
reg   [0:0] icmp_ln668_reg_1232_pp0_iter10_reg;
reg   [7:0] src_buf1_V_5_reg_1236;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter4_reg;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter5_reg;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter6_reg;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter7_reg;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter8_reg;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter9_reg;
reg   [7:0] src_buf1_V_5_reg_1236_pp0_iter10_reg;
reg   [7:0] src_buf1_V_6_reg_1242;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter4_reg;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter5_reg;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter6_reg;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter7_reg;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter8_reg;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter9_reg;
reg   [7:0] src_buf1_V_6_reg_1242_pp0_iter10_reg;
reg   [7:0] src_buf1_V_7_reg_1248;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter4_reg;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter5_reg;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter6_reg;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter7_reg;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter8_reg;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter9_reg;
reg   [7:0] src_buf1_V_7_reg_1248_pp0_iter10_reg;
reg   [7:0] src_buf2_V_5_reg_1254;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter4_reg;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter5_reg;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter6_reg;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter7_reg;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter8_reg;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter9_reg;
reg   [7:0] src_buf2_V_5_reg_1254_pp0_iter10_reg;
reg   [7:0] src_buf2_V_6_reg_1260;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter4_reg;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter5_reg;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter6_reg;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter7_reg;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter8_reg;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter9_reg;
reg   [7:0] src_buf2_V_6_reg_1260_pp0_iter10_reg;
reg   [7:0] src_buf2_V_7_reg_1266;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter4_reg;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter5_reg;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter6_reg;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter7_reg;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter8_reg;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter9_reg;
reg   [7:0] src_buf2_V_7_reg_1266_pp0_iter10_reg;
reg   [7:0] src_buf3_V_5_reg_1272;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter4_reg;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter5_reg;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter6_reg;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter7_reg;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter8_reg;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter9_reg;
reg   [7:0] src_buf3_V_5_reg_1272_pp0_iter10_reg;
reg   [7:0] src_buf3_V_6_reg_1278;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter4_reg;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter5_reg;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter6_reg;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter7_reg;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter8_reg;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter9_reg;
reg   [7:0] src_buf3_V_6_reg_1278_pp0_iter10_reg;
reg   [7:0] src_buf3_V_7_reg_1284;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter4_reg;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter5_reg;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter6_reg;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter7_reg;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter8_reg;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter9_reg;
reg   [7:0] src_buf3_V_7_reg_1284_pp0_iter10_reg;
reg   [7:0] src_buf4_V_5_reg_1290;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter4_reg;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter5_reg;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter6_reg;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter7_reg;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter8_reg;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter9_reg;
reg   [7:0] src_buf4_V_5_reg_1290_pp0_iter10_reg;
reg   [7:0] src_buf4_V_6_reg_1296;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter4_reg;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter5_reg;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter6_reg;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter7_reg;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter8_reg;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter9_reg;
reg   [7:0] src_buf4_V_6_reg_1296_pp0_iter10_reg;
reg   [7:0] src_buf4_V_7_reg_1302;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter4_reg;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter5_reg;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter6_reg;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter7_reg;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter8_reg;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter9_reg;
reg   [7:0] src_buf4_V_7_reg_1302_pp0_iter10_reg;
reg   [7:0] src_buf5_V_5_reg_1308;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter4_reg;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter5_reg;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter6_reg;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter7_reg;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter8_reg;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter9_reg;
reg   [7:0] src_buf5_V_5_reg_1308_pp0_iter10_reg;
reg   [7:0] src_buf5_V_6_reg_1314;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter4_reg;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter5_reg;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter6_reg;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter7_reg;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter8_reg;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter9_reg;
reg   [7:0] src_buf5_V_6_reg_1314_pp0_iter10_reg;
reg   [7:0] src_buf5_V_7_reg_1320;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter4_reg;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter5_reg;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter6_reg;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter7_reg;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter8_reg;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter9_reg;
reg   [7:0] src_buf5_V_7_reg_1320_pp0_iter10_reg;
wire   [7:0] src_buf1_V_3_fu_797_p7;
wire   [7:0] src_buf2_V_3_fu_813_p7;
wire   [7:0] src_buf3_V_3_fu_829_p7;
wire   [7:0] src_buf4_V_3_fu_845_p7;
wire   [7:0] src_buf5_V_3_fu_861_p7;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    grp_xfapplygaussian5x5_1_0_false_s_fu_536_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call15;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call15;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call15;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call15;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call15;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call15;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call15;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call15;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call15;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call15;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call15;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call15;
reg    ap_block_state13_pp0_stage0_iter12_ignore_call15;
reg    ap_block_pp0_stage0_11001_ignoreCallOp154;
wire   [63:0] zext_ln541_fu_694_p1;
reg   [9:0] col_V_fu_144;
wire   [9:0] col_V_4_fu_683_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_col_V_3;
reg   [7:0] src_buf1_V_4_fu_148;
reg   [7:0] src_buf2_V_4_fu_152;
reg   [7:0] src_buf3_V_4_fu_156;
reg   [7:0] src_buf4_V_4_fu_160;
reg   [7:0] src_buf5_V_4_fu_164;
reg   [7:0] src_buf1_V_fu_168;
reg   [7:0] src_buf1_V_1_fu_172;
reg   [7:0] src_buf1_V_2_fu_176;
reg   [7:0] src_buf2_V_fu_180;
reg   [7:0] src_buf2_V_1_fu_184;
reg   [7:0] src_buf2_V_2_fu_188;
reg   [7:0] src_buf3_V_fu_192;
reg   [7:0] src_buf3_V_1_fu_196;
reg   [7:0] src_buf3_V_2_fu_200;
reg   [7:0] src_buf4_V_fu_204;
reg   [7:0] src_buf4_V_1_fu_208;
reg   [7:0] src_buf4_V_2_fu_212;
reg   [7:0] src_buf5_V_fu_216;
reg   [7:0] src_buf5_V_1_fu_220;
reg   [7:0] src_buf5_V_2_fu_224;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] tmp_fu_702_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_806;
reg    ap_condition_1132;
reg    ap_condition_1138;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

accelerator_v2_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U167(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(buf_V_3_q0),
    .din4(buf_V_4_q0),
    .din5(tp1_V_cast),
    .dout(src_buf1_V_3_fu_797_p7)
);

accelerator_v2_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U168(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(buf_V_3_q0),
    .din4(buf_V_4_q0),
    .din5(tp2_V_cast),
    .dout(src_buf2_V_3_fu_813_p7)
);

accelerator_v2_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U169(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(buf_V_3_q0),
    .din4(buf_V_4_q0),
    .din5(mid_V_cast),
    .dout(src_buf3_V_3_fu_829_p7)
);

accelerator_v2_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U170(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(buf_V_3_q0),
    .din4(buf_V_4_q0),
    .din5(bottom1_V_cast),
    .dout(src_buf4_V_3_fu_845_p7)
);

accelerator_v2_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U171(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(buf_V_3_q0),
    .din4(buf_V_4_q0),
    .din5(bottom2_V_cast),
    .dout(src_buf5_V_3_fu_861_p7)
);

accelerator_v2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln624_fu_677_p2 == 1'd0))) begin
            col_V_fu_144 <= col_V_4_fu_683_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_V_fu_144 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf1_V_1_fu_172 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf1_V_1_fu_172 <= src_buf1_V_2_fu_176;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf1_V_2_fu_176 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf1_V_2_fu_176 <= src_buf1_V_3_fu_797_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf1_V_4_fu_148 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf1_V_4_fu_148 <= src_buf1_V_fu_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf1_V_fu_168 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf1_V_fu_168 <= src_buf1_V_1_fu_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf2_V_1_fu_184 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf2_V_1_fu_184 <= src_buf2_V_2_fu_188;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf2_V_2_fu_188 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf2_V_2_fu_188 <= src_buf2_V_3_fu_813_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf2_V_4_fu_152 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf2_V_4_fu_152 <= src_buf2_V_fu_180;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf2_V_fu_180 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf2_V_fu_180 <= src_buf2_V_1_fu_184;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf3_V_1_fu_196 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf3_V_1_fu_196 <= src_buf3_V_2_fu_200;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf3_V_2_fu_200 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf3_V_2_fu_200 <= src_buf3_V_3_fu_829_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf3_V_4_fu_156 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf3_V_4_fu_156 <= src_buf3_V_fu_192;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf3_V_fu_192 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf3_V_fu_192 <= src_buf3_V_1_fu_196;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf4_V_1_fu_208 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf4_V_1_fu_208 <= src_buf4_V_2_fu_212;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf4_V_2_fu_212 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf4_V_2_fu_212 <= src_buf4_V_3_fu_845_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf4_V_4_fu_160 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf4_V_4_fu_160 <= src_buf4_V_fu_204;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf4_V_fu_204 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf4_V_fu_204 <= src_buf4_V_1_fu_208;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf5_V_1_fu_220 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf5_V_1_fu_220 <= src_buf5_V_2_fu_224;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf5_V_2_fu_224 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf5_V_2_fu_224 <= src_buf5_V_3_fu_861_p7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf5_V_4_fu_164 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf5_V_4_fu_164 <= src_buf5_V_fu_216;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            src_buf5_V_fu_216 <= 8'd0;
        end else if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            src_buf5_V_fu_216 <= src_buf5_V_1_fu_220;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln624_reg_1203_pp0_iter10_reg <= icmp_ln624_reg_1203_pp0_iter9_reg;
        icmp_ln624_reg_1203_pp0_iter2_reg <= icmp_ln624_reg_1203_pp0_iter1_reg;
        icmp_ln624_reg_1203_pp0_iter3_reg <= icmp_ln624_reg_1203_pp0_iter2_reg;
        icmp_ln624_reg_1203_pp0_iter4_reg <= icmp_ln624_reg_1203_pp0_iter3_reg;
        icmp_ln624_reg_1203_pp0_iter5_reg <= icmp_ln624_reg_1203_pp0_iter4_reg;
        icmp_ln624_reg_1203_pp0_iter6_reg <= icmp_ln624_reg_1203_pp0_iter5_reg;
        icmp_ln624_reg_1203_pp0_iter7_reg <= icmp_ln624_reg_1203_pp0_iter6_reg;
        icmp_ln624_reg_1203_pp0_iter8_reg <= icmp_ln624_reg_1203_pp0_iter7_reg;
        icmp_ln624_reg_1203_pp0_iter9_reg <= icmp_ln624_reg_1203_pp0_iter8_reg;
        icmp_ln668_reg_1232_pp0_iter10_reg <= icmp_ln668_reg_1232_pp0_iter9_reg;
        icmp_ln668_reg_1232_pp0_iter11_reg <= icmp_ln668_reg_1232_pp0_iter10_reg;
        icmp_ln668_reg_1232_pp0_iter2_reg <= icmp_ln668_reg_1232;
        icmp_ln668_reg_1232_pp0_iter3_reg <= icmp_ln668_reg_1232_pp0_iter2_reg;
        icmp_ln668_reg_1232_pp0_iter4_reg <= icmp_ln668_reg_1232_pp0_iter3_reg;
        icmp_ln668_reg_1232_pp0_iter5_reg <= icmp_ln668_reg_1232_pp0_iter4_reg;
        icmp_ln668_reg_1232_pp0_iter6_reg <= icmp_ln668_reg_1232_pp0_iter5_reg;
        icmp_ln668_reg_1232_pp0_iter7_reg <= icmp_ln668_reg_1232_pp0_iter6_reg;
        icmp_ln668_reg_1232_pp0_iter8_reg <= icmp_ln668_reg_1232_pp0_iter7_reg;
        icmp_ln668_reg_1232_pp0_iter9_reg <= icmp_ln668_reg_1232_pp0_iter8_reg;
        src_buf1_V_5_reg_1236_pp0_iter10_reg <= src_buf1_V_5_reg_1236_pp0_iter9_reg;
        src_buf1_V_5_reg_1236_pp0_iter4_reg <= src_buf1_V_5_reg_1236;
        src_buf1_V_5_reg_1236_pp0_iter5_reg <= src_buf1_V_5_reg_1236_pp0_iter4_reg;
        src_buf1_V_5_reg_1236_pp0_iter6_reg <= src_buf1_V_5_reg_1236_pp0_iter5_reg;
        src_buf1_V_5_reg_1236_pp0_iter7_reg <= src_buf1_V_5_reg_1236_pp0_iter6_reg;
        src_buf1_V_5_reg_1236_pp0_iter8_reg <= src_buf1_V_5_reg_1236_pp0_iter7_reg;
        src_buf1_V_5_reg_1236_pp0_iter9_reg <= src_buf1_V_5_reg_1236_pp0_iter8_reg;
        src_buf1_V_6_reg_1242_pp0_iter10_reg <= src_buf1_V_6_reg_1242_pp0_iter9_reg;
        src_buf1_V_6_reg_1242_pp0_iter4_reg <= src_buf1_V_6_reg_1242;
        src_buf1_V_6_reg_1242_pp0_iter5_reg <= src_buf1_V_6_reg_1242_pp0_iter4_reg;
        src_buf1_V_6_reg_1242_pp0_iter6_reg <= src_buf1_V_6_reg_1242_pp0_iter5_reg;
        src_buf1_V_6_reg_1242_pp0_iter7_reg <= src_buf1_V_6_reg_1242_pp0_iter6_reg;
        src_buf1_V_6_reg_1242_pp0_iter8_reg <= src_buf1_V_6_reg_1242_pp0_iter7_reg;
        src_buf1_V_6_reg_1242_pp0_iter9_reg <= src_buf1_V_6_reg_1242_pp0_iter8_reg;
        src_buf1_V_7_reg_1248_pp0_iter10_reg <= src_buf1_V_7_reg_1248_pp0_iter9_reg;
        src_buf1_V_7_reg_1248_pp0_iter4_reg <= src_buf1_V_7_reg_1248;
        src_buf1_V_7_reg_1248_pp0_iter5_reg <= src_buf1_V_7_reg_1248_pp0_iter4_reg;
        src_buf1_V_7_reg_1248_pp0_iter6_reg <= src_buf1_V_7_reg_1248_pp0_iter5_reg;
        src_buf1_V_7_reg_1248_pp0_iter7_reg <= src_buf1_V_7_reg_1248_pp0_iter6_reg;
        src_buf1_V_7_reg_1248_pp0_iter8_reg <= src_buf1_V_7_reg_1248_pp0_iter7_reg;
        src_buf1_V_7_reg_1248_pp0_iter9_reg <= src_buf1_V_7_reg_1248_pp0_iter8_reg;
        src_buf2_V_5_reg_1254_pp0_iter10_reg <= src_buf2_V_5_reg_1254_pp0_iter9_reg;
        src_buf2_V_5_reg_1254_pp0_iter4_reg <= src_buf2_V_5_reg_1254;
        src_buf2_V_5_reg_1254_pp0_iter5_reg <= src_buf2_V_5_reg_1254_pp0_iter4_reg;
        src_buf2_V_5_reg_1254_pp0_iter6_reg <= src_buf2_V_5_reg_1254_pp0_iter5_reg;
        src_buf2_V_5_reg_1254_pp0_iter7_reg <= src_buf2_V_5_reg_1254_pp0_iter6_reg;
        src_buf2_V_5_reg_1254_pp0_iter8_reg <= src_buf2_V_5_reg_1254_pp0_iter7_reg;
        src_buf2_V_5_reg_1254_pp0_iter9_reg <= src_buf2_V_5_reg_1254_pp0_iter8_reg;
        src_buf2_V_6_reg_1260_pp0_iter10_reg <= src_buf2_V_6_reg_1260_pp0_iter9_reg;
        src_buf2_V_6_reg_1260_pp0_iter4_reg <= src_buf2_V_6_reg_1260;
        src_buf2_V_6_reg_1260_pp0_iter5_reg <= src_buf2_V_6_reg_1260_pp0_iter4_reg;
        src_buf2_V_6_reg_1260_pp0_iter6_reg <= src_buf2_V_6_reg_1260_pp0_iter5_reg;
        src_buf2_V_6_reg_1260_pp0_iter7_reg <= src_buf2_V_6_reg_1260_pp0_iter6_reg;
        src_buf2_V_6_reg_1260_pp0_iter8_reg <= src_buf2_V_6_reg_1260_pp0_iter7_reg;
        src_buf2_V_6_reg_1260_pp0_iter9_reg <= src_buf2_V_6_reg_1260_pp0_iter8_reg;
        src_buf2_V_7_reg_1266_pp0_iter10_reg <= src_buf2_V_7_reg_1266_pp0_iter9_reg;
        src_buf2_V_7_reg_1266_pp0_iter4_reg <= src_buf2_V_7_reg_1266;
        src_buf2_V_7_reg_1266_pp0_iter5_reg <= src_buf2_V_7_reg_1266_pp0_iter4_reg;
        src_buf2_V_7_reg_1266_pp0_iter6_reg <= src_buf2_V_7_reg_1266_pp0_iter5_reg;
        src_buf2_V_7_reg_1266_pp0_iter7_reg <= src_buf2_V_7_reg_1266_pp0_iter6_reg;
        src_buf2_V_7_reg_1266_pp0_iter8_reg <= src_buf2_V_7_reg_1266_pp0_iter7_reg;
        src_buf2_V_7_reg_1266_pp0_iter9_reg <= src_buf2_V_7_reg_1266_pp0_iter8_reg;
        src_buf3_V_5_reg_1272_pp0_iter10_reg <= src_buf3_V_5_reg_1272_pp0_iter9_reg;
        src_buf3_V_5_reg_1272_pp0_iter4_reg <= src_buf3_V_5_reg_1272;
        src_buf3_V_5_reg_1272_pp0_iter5_reg <= src_buf3_V_5_reg_1272_pp0_iter4_reg;
        src_buf3_V_5_reg_1272_pp0_iter6_reg <= src_buf3_V_5_reg_1272_pp0_iter5_reg;
        src_buf3_V_5_reg_1272_pp0_iter7_reg <= src_buf3_V_5_reg_1272_pp0_iter6_reg;
        src_buf3_V_5_reg_1272_pp0_iter8_reg <= src_buf3_V_5_reg_1272_pp0_iter7_reg;
        src_buf3_V_5_reg_1272_pp0_iter9_reg <= src_buf3_V_5_reg_1272_pp0_iter8_reg;
        src_buf3_V_6_reg_1278_pp0_iter10_reg <= src_buf3_V_6_reg_1278_pp0_iter9_reg;
        src_buf3_V_6_reg_1278_pp0_iter4_reg <= src_buf3_V_6_reg_1278;
        src_buf3_V_6_reg_1278_pp0_iter5_reg <= src_buf3_V_6_reg_1278_pp0_iter4_reg;
        src_buf3_V_6_reg_1278_pp0_iter6_reg <= src_buf3_V_6_reg_1278_pp0_iter5_reg;
        src_buf3_V_6_reg_1278_pp0_iter7_reg <= src_buf3_V_6_reg_1278_pp0_iter6_reg;
        src_buf3_V_6_reg_1278_pp0_iter8_reg <= src_buf3_V_6_reg_1278_pp0_iter7_reg;
        src_buf3_V_6_reg_1278_pp0_iter9_reg <= src_buf3_V_6_reg_1278_pp0_iter8_reg;
        src_buf3_V_7_reg_1284_pp0_iter10_reg <= src_buf3_V_7_reg_1284_pp0_iter9_reg;
        src_buf3_V_7_reg_1284_pp0_iter4_reg <= src_buf3_V_7_reg_1284;
        src_buf3_V_7_reg_1284_pp0_iter5_reg <= src_buf3_V_7_reg_1284_pp0_iter4_reg;
        src_buf3_V_7_reg_1284_pp0_iter6_reg <= src_buf3_V_7_reg_1284_pp0_iter5_reg;
        src_buf3_V_7_reg_1284_pp0_iter7_reg <= src_buf3_V_7_reg_1284_pp0_iter6_reg;
        src_buf3_V_7_reg_1284_pp0_iter8_reg <= src_buf3_V_7_reg_1284_pp0_iter7_reg;
        src_buf3_V_7_reg_1284_pp0_iter9_reg <= src_buf3_V_7_reg_1284_pp0_iter8_reg;
        src_buf4_V_5_reg_1290_pp0_iter10_reg <= src_buf4_V_5_reg_1290_pp0_iter9_reg;
        src_buf4_V_5_reg_1290_pp0_iter4_reg <= src_buf4_V_5_reg_1290;
        src_buf4_V_5_reg_1290_pp0_iter5_reg <= src_buf4_V_5_reg_1290_pp0_iter4_reg;
        src_buf4_V_5_reg_1290_pp0_iter6_reg <= src_buf4_V_5_reg_1290_pp0_iter5_reg;
        src_buf4_V_5_reg_1290_pp0_iter7_reg <= src_buf4_V_5_reg_1290_pp0_iter6_reg;
        src_buf4_V_5_reg_1290_pp0_iter8_reg <= src_buf4_V_5_reg_1290_pp0_iter7_reg;
        src_buf4_V_5_reg_1290_pp0_iter9_reg <= src_buf4_V_5_reg_1290_pp0_iter8_reg;
        src_buf4_V_6_reg_1296_pp0_iter10_reg <= src_buf4_V_6_reg_1296_pp0_iter9_reg;
        src_buf4_V_6_reg_1296_pp0_iter4_reg <= src_buf4_V_6_reg_1296;
        src_buf4_V_6_reg_1296_pp0_iter5_reg <= src_buf4_V_6_reg_1296_pp0_iter4_reg;
        src_buf4_V_6_reg_1296_pp0_iter6_reg <= src_buf4_V_6_reg_1296_pp0_iter5_reg;
        src_buf4_V_6_reg_1296_pp0_iter7_reg <= src_buf4_V_6_reg_1296_pp0_iter6_reg;
        src_buf4_V_6_reg_1296_pp0_iter8_reg <= src_buf4_V_6_reg_1296_pp0_iter7_reg;
        src_buf4_V_6_reg_1296_pp0_iter9_reg <= src_buf4_V_6_reg_1296_pp0_iter8_reg;
        src_buf4_V_7_reg_1302_pp0_iter10_reg <= src_buf4_V_7_reg_1302_pp0_iter9_reg;
        src_buf4_V_7_reg_1302_pp0_iter4_reg <= src_buf4_V_7_reg_1302;
        src_buf4_V_7_reg_1302_pp0_iter5_reg <= src_buf4_V_7_reg_1302_pp0_iter4_reg;
        src_buf4_V_7_reg_1302_pp0_iter6_reg <= src_buf4_V_7_reg_1302_pp0_iter5_reg;
        src_buf4_V_7_reg_1302_pp0_iter7_reg <= src_buf4_V_7_reg_1302_pp0_iter6_reg;
        src_buf4_V_7_reg_1302_pp0_iter8_reg <= src_buf4_V_7_reg_1302_pp0_iter7_reg;
        src_buf4_V_7_reg_1302_pp0_iter9_reg <= src_buf4_V_7_reg_1302_pp0_iter8_reg;
        src_buf5_V_5_reg_1308_pp0_iter10_reg <= src_buf5_V_5_reg_1308_pp0_iter9_reg;
        src_buf5_V_5_reg_1308_pp0_iter4_reg <= src_buf5_V_5_reg_1308;
        src_buf5_V_5_reg_1308_pp0_iter5_reg <= src_buf5_V_5_reg_1308_pp0_iter4_reg;
        src_buf5_V_5_reg_1308_pp0_iter6_reg <= src_buf5_V_5_reg_1308_pp0_iter5_reg;
        src_buf5_V_5_reg_1308_pp0_iter7_reg <= src_buf5_V_5_reg_1308_pp0_iter6_reg;
        src_buf5_V_5_reg_1308_pp0_iter8_reg <= src_buf5_V_5_reg_1308_pp0_iter7_reg;
        src_buf5_V_5_reg_1308_pp0_iter9_reg <= src_buf5_V_5_reg_1308_pp0_iter8_reg;
        src_buf5_V_6_reg_1314_pp0_iter10_reg <= src_buf5_V_6_reg_1314_pp0_iter9_reg;
        src_buf5_V_6_reg_1314_pp0_iter4_reg <= src_buf5_V_6_reg_1314;
        src_buf5_V_6_reg_1314_pp0_iter5_reg <= src_buf5_V_6_reg_1314_pp0_iter4_reg;
        src_buf5_V_6_reg_1314_pp0_iter6_reg <= src_buf5_V_6_reg_1314_pp0_iter5_reg;
        src_buf5_V_6_reg_1314_pp0_iter7_reg <= src_buf5_V_6_reg_1314_pp0_iter6_reg;
        src_buf5_V_6_reg_1314_pp0_iter8_reg <= src_buf5_V_6_reg_1314_pp0_iter7_reg;
        src_buf5_V_6_reg_1314_pp0_iter9_reg <= src_buf5_V_6_reg_1314_pp0_iter8_reg;
        src_buf5_V_7_reg_1320_pp0_iter10_reg <= src_buf5_V_7_reg_1320_pp0_iter9_reg;
        src_buf5_V_7_reg_1320_pp0_iter4_reg <= src_buf5_V_7_reg_1320;
        src_buf5_V_7_reg_1320_pp0_iter5_reg <= src_buf5_V_7_reg_1320_pp0_iter4_reg;
        src_buf5_V_7_reg_1320_pp0_iter6_reg <= src_buf5_V_7_reg_1320_pp0_iter5_reg;
        src_buf5_V_7_reg_1320_pp0_iter7_reg <= src_buf5_V_7_reg_1320_pp0_iter6_reg;
        src_buf5_V_7_reg_1320_pp0_iter8_reg <= src_buf5_V_7_reg_1320_pp0_iter7_reg;
        src_buf5_V_7_reg_1320_pp0_iter9_reg <= src_buf5_V_7_reg_1320_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        col_V_3_reg_1197 <= ap_sig_allocacmp_col_V_3;
        icmp_ln624_reg_1203 <= icmp_ln624_fu_677_p2;
        icmp_ln624_reg_1203_pp0_iter1_reg <= icmp_ln624_reg_1203;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln624_reg_1203 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_1_addr_reg_1212 <= zext_ln541_fu_694_p1;
        buf_V_2_addr_reg_1217 <= zext_ln541_fu_694_p1;
        buf_V_3_addr_reg_1222 <= zext_ln541_fu_694_p1;
        buf_V_4_addr_reg_1227 <= zext_ln541_fu_694_p1;
        buf_V_addr_reg_1207 <= zext_ln541_fu_694_p1;
        icmp_ln668_reg_1232 <= icmp_ln668_fu_711_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf1_V_5_reg_1236 <= src_buf1_V_fu_168;
        src_buf1_V_6_reg_1242 <= src_buf1_V_1_fu_172;
        src_buf1_V_7_reg_1248 <= src_buf1_V_2_fu_176;
        src_buf2_V_5_reg_1254 <= src_buf2_V_fu_180;
        src_buf2_V_6_reg_1260 <= src_buf2_V_1_fu_184;
        src_buf2_V_7_reg_1266 <= src_buf2_V_2_fu_188;
        src_buf3_V_5_reg_1272 <= src_buf3_V_fu_192;
        src_buf3_V_6_reg_1278 <= src_buf3_V_1_fu_196;
        src_buf3_V_7_reg_1284 <= src_buf3_V_2_fu_200;
        src_buf4_V_5_reg_1290 <= src_buf4_V_fu_204;
        src_buf4_V_6_reg_1296 <= src_buf4_V_1_fu_208;
        src_buf4_V_7_reg_1302 <= src_buf4_V_2_fu_212;
        src_buf5_V_5_reg_1308 <= src_buf5_V_fu_216;
        src_buf5_V_6_reg_1314 <= src_buf5_V_1_fu_220;
        src_buf5_V_7_reg_1320 <= src_buf5_V_2_fu_224;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln624_fu_677_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_col_V_3 = 10'd0;
    end else begin
        ap_sig_allocacmp_col_V_3 = col_V_fu_144;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0))) begin
        blurred_mat_data45_blk_n = blurred_mat_data45_full_n;
    end else begin
        blurred_mat_data45_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0))) begin
        blurred_mat_data45_write = 1'b1;
    end else begin
        blurred_mat_data45_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_1_ce1 = 1'b1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_806)) begin
        if (((cmp_i_i380_i == 1'd1) & (row_ind_V_cast_read_reg_1153 == 3'd1))) begin
            buf_V_1_d1 = gray_mat_data44_dout;
        end else if (((cmp_i_i380_i_read_reg_1149 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd1))) begin
            buf_V_1_d1 = 8'd0;
        end else begin
            buf_V_1_d1 = 'bx;
        end
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_1_we1 = 1'b1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_2_ce1 = 1'b1;
    end else begin
        buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_806)) begin
        if (((cmp_i_i380_i == 1'd1) & (row_ind_V_cast_read_reg_1153 == 3'd2))) begin
            buf_V_2_d1 = gray_mat_data44_dout;
        end else if (((cmp_i_i380_i_read_reg_1149 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd2))) begin
            buf_V_2_d1 = 8'd0;
        end else begin
            buf_V_2_d1 = 'bx;
        end
    end else begin
        buf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_2_we1 = 1'b1;
    end else begin
        buf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_3_ce0 = 1'b1;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_3_ce1 = 1'b1;
    end else begin
        buf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_806)) begin
        if (((cmp_i_i380_i == 1'd1) & (row_ind_V_cast_read_reg_1153 == 3'd3))) begin
            buf_V_3_d1 = gray_mat_data44_dout;
        end else if (((cmp_i_i380_i_read_reg_1149 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd3))) begin
            buf_V_3_d1 = 8'd0;
        end else begin
            buf_V_3_d1 = 'bx;
        end
    end else begin
        buf_V_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_3_we1 = 1'b1;
    end else begin
        buf_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_4_ce0 = 1'b1;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(row_ind_V_cast_read_reg_1153 == 3'd0) & ~(row_ind_V_cast_read_reg_1153 == 3'd1) & ~(row_ind_V_cast_read_reg_1153 == 3'd2) & ~(row_ind_V_cast_read_reg_1153 == 3'd3) & (cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(bottom2_V_cast_read_reg_1172 == 3'd0) & ~(bottom2_V_cast_read_reg_1172 == 3'd1) & ~(bottom2_V_cast_read_reg_1172 == 3'd2) & ~(bottom2_V_cast_read_reg_1172 == 3'd3) & (cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_4_ce1 = 1'b1;
    end else begin
        buf_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_806)) begin
        if ((1'b1 == ap_condition_1138)) begin
            buf_V_4_d1 = gray_mat_data44_dout;
        end else if ((1'b1 == ap_condition_1132)) begin
            buf_V_4_d1 = 8'd0;
        end else begin
            buf_V_4_d1 = 'bx;
        end
    end else begin
        buf_V_4_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(row_ind_V_cast_read_reg_1153 == 3'd0) & ~(row_ind_V_cast_read_reg_1153 == 3'd1) & ~(row_ind_V_cast_read_reg_1153 == 3'd2) & ~(row_ind_V_cast_read_reg_1153 == 3'd3) & (cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(bottom2_V_cast_read_reg_1172 == 3'd0) & ~(bottom2_V_cast_read_reg_1172 == 3'd1) & ~(bottom2_V_cast_read_reg_1172 == 3'd2) & ~(bottom2_V_cast_read_reg_1172 == 3'd3) & (cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_4_we1 = 1'b1;
    end else begin
        buf_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_ce1 = 1'b1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_806)) begin
        if (((cmp_i_i380_i == 1'd1) & (row_ind_V_cast_read_reg_1153 == 3'd0))) begin
            buf_V_d1 = gray_mat_data44_dout;
        end else if (((cmp_i_i380_i_read_reg_1149 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd0))) begin
            buf_V_d1 = 8'd0;
        end else begin
            buf_V_d1 = 'bx;
        end
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i380_i_read_reg_1149 == 1'd0) & (icmp_ln624_reg_1203 == 1'd0) & (bottom2_V_cast_read_reg_1172 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0) & (row_ind_V_cast_read_reg_1153 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_we1 = 1'b1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op105_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gray_mat_data44_blk_n = gray_mat_data44_empty_n;
    end else begin
        gray_mat_data44_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op105_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gray_mat_data44_read = 1'b1;
    end else begin
        gray_mat_data44_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp154))) begin
        grp_xfapplygaussian5x5_1_0_false_s_fu_536_ap_ce = 1'b1;
    end else begin
        grp_xfapplygaussian5x5_1_0_false_s_fu_536_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf1_V_0_out_ap_vld = 1'b1;
    end else begin
        src_buf1_V_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf1_V_1_out_ap_vld = 1'b1;
    end else begin
        src_buf1_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf1_V_2_out_ap_vld = 1'b1;
    end else begin
        src_buf1_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf1_V_out_ap_vld = 1'b1;
    end else begin
        src_buf1_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf2_V_0_out_ap_vld = 1'b1;
    end else begin
        src_buf2_V_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf2_V_1_out_ap_vld = 1'b1;
    end else begin
        src_buf2_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf2_V_2_out_ap_vld = 1'b1;
    end else begin
        src_buf2_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf2_V_out_ap_vld = 1'b1;
    end else begin
        src_buf2_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf3_V_0_out_ap_vld = 1'b1;
    end else begin
        src_buf3_V_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf3_V_1_out_ap_vld = 1'b1;
    end else begin
        src_buf3_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf3_V_2_out_ap_vld = 1'b1;
    end else begin
        src_buf3_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf3_V_out_ap_vld = 1'b1;
    end else begin
        src_buf3_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf4_V_0_out_ap_vld = 1'b1;
    end else begin
        src_buf4_V_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf4_V_1_out_ap_vld = 1'b1;
    end else begin
        src_buf4_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf4_V_2_out_ap_vld = 1'b1;
    end else begin
        src_buf4_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf4_V_out_ap_vld = 1'b1;
    end else begin
        src_buf4_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf5_V_0_out_ap_vld = 1'b1;
    end else begin
        src_buf5_V_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf5_V_1_out_ap_vld = 1'b1;
    end else begin
        src_buf5_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf5_V_2_out_ap_vld = 1'b1;
    end else begin
        src_buf5_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_1203_pp0_iter10_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_buf5_V_out_ap_vld = 1'b1;
    end else begin
        src_buf5_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((blurred_mat_data45_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0)) | ((ap_predicate_op105_read_state2 == 1'b1) & (gray_mat_data44_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((blurred_mat_data45_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0)) | ((ap_predicate_op105_read_state2 == 1'b1) & (gray_mat_data44_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp154 = (((blurred_mat_data45_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0)) | ((ap_predicate_op105_read_state2 == 1'b1) & (gray_mat_data44_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((blurred_mat_data45_full_n == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0)) | ((ap_predicate_op105_read_state2 == 1'b1) & (gray_mat_data44_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_pp0_stage0_iter12 = ((blurred_mat_data45_full_n == 1'b0) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter12_ignore_call15 = ((blurred_mat_data45_full_n == 1'b0) & (icmp_ln668_reg_1232_pp0_iter11_reg == 1'd0));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op105_read_state2 == 1'b1) & (gray_mat_data44_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call15 = ((ap_predicate_op105_read_state2 == 1'b1) & (gray_mat_data44_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1132 = (~(bottom2_V_cast_read_reg_1172 == 3'd0) & ~(bottom2_V_cast_read_reg_1172 == 3'd1) & ~(bottom2_V_cast_read_reg_1172 == 3'd2) & ~(bottom2_V_cast_read_reg_1172 == 3'd3) & (cmp_i_i380_i_read_reg_1149 == 1'd0));
end

always @ (*) begin
    ap_condition_1138 = (~(row_ind_V_cast_read_reg_1153 == 3'd0) & ~(row_ind_V_cast_read_reg_1153 == 3'd1) & ~(row_ind_V_cast_read_reg_1153 == 3'd2) & ~(row_ind_V_cast_read_reg_1153 == 3'd3) & (cmp_i_i380_i == 1'd1));
end

always @ (*) begin
    ap_condition_806 = ((icmp_ln624_reg_1203 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op105_read_state2 = ((cmp_i_i380_i == 1'd1) & (icmp_ln624_reg_1203 == 1'd0));
end

assign blurred_mat_data45_din = grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_dout0;

assign bottom2_V_cast_read_reg_1172 = bottom2_V_cast;

assign buf_V_1_address0 = buf_V_1_addr_reg_1212;

assign buf_V_1_address1 = zext_ln541_fu_694_p1;

assign buf_V_2_address0 = buf_V_2_addr_reg_1217;

assign buf_V_2_address1 = zext_ln541_fu_694_p1;

assign buf_V_3_address0 = buf_V_3_addr_reg_1222;

assign buf_V_3_address1 = zext_ln541_fu_694_p1;

assign buf_V_4_address0 = buf_V_4_addr_reg_1227;

assign buf_V_4_address1 = zext_ln541_fu_694_p1;

assign buf_V_address0 = buf_V_addr_reg_1207;

assign buf_V_address1 = zext_ln541_fu_694_p1;

assign cmp_i_i380_i_read_reg_1149 = cmp_i_i380_i;

assign col_V_4_fu_683_p2 = (ap_sig_allocacmp_col_V_3 + 10'd1);

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_ce = grp_xfapplygaussian5x5_1_0_false_s_fu_536_ap_ce;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din1 = src_buf1_V_4_fu_148;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din10 = src_buf2_V_3_fu_813_p7;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din11 = src_buf3_V_4_fu_156;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din12 = src_buf3_V_fu_192;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din13 = src_buf3_V_1_fu_196;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din14 = src_buf3_V_2_fu_200;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din15 = src_buf3_V_3_fu_829_p7;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din16 = src_buf4_V_4_fu_160;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din17 = src_buf4_V_fu_204;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din18 = src_buf4_V_1_fu_208;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din19 = src_buf4_V_2_fu_212;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din2 = src_buf1_V_fu_168;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din20 = src_buf4_V_3_fu_845_p7;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din21 = src_buf5_V_4_fu_164;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din22 = src_buf5_V_fu_216;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din23 = src_buf5_V_1_fu_220;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din24 = src_buf5_V_2_fu_224;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din25 = src_buf5_V_3_fu_861_p7;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din26 = p_read;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din27 = p_read1;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din28 = p_read2;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din3 = src_buf1_V_1_fu_172;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din4 = src_buf1_V_2_fu_176;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din5 = src_buf1_V_3_fu_797_p7;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din6 = src_buf2_V_4_fu_152;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din7 = src_buf2_V_fu_180;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din8 = src_buf2_V_1_fu_184;

assign grp_xfapplygaussian5x5_1_0_false_s_fu_243_p_din9 = src_buf2_V_2_fu_188;

assign icmp_ln624_fu_677_p2 = ((ap_sig_allocacmp_col_V_3 == 10'd644) ? 1'b1 : 1'b0);

assign icmp_ln668_fu_711_p2 = ((tmp_fu_702_p4 == 9'd0) ? 1'b1 : 1'b0);

assign row_ind_V_cast_read_reg_1153 = row_ind_V_cast;

assign src_buf1_V_0_out = src_buf1_V_4_fu_148;

assign src_buf1_V_1_out = src_buf1_V_6_reg_1242_pp0_iter10_reg;

assign src_buf1_V_2_out = src_buf1_V_7_reg_1248_pp0_iter10_reg;

assign src_buf1_V_out = src_buf1_V_5_reg_1236_pp0_iter10_reg;

assign src_buf2_V_0_out = src_buf2_V_4_fu_152;

assign src_buf2_V_1_out = src_buf2_V_6_reg_1260_pp0_iter10_reg;

assign src_buf2_V_2_out = src_buf2_V_7_reg_1266_pp0_iter10_reg;

assign src_buf2_V_out = src_buf2_V_5_reg_1254_pp0_iter10_reg;

assign src_buf3_V_0_out = src_buf3_V_4_fu_156;

assign src_buf3_V_1_out = src_buf3_V_6_reg_1278_pp0_iter10_reg;

assign src_buf3_V_2_out = src_buf3_V_7_reg_1284_pp0_iter10_reg;

assign src_buf3_V_out = src_buf3_V_5_reg_1272_pp0_iter10_reg;

assign src_buf4_V_0_out = src_buf4_V_4_fu_160;

assign src_buf4_V_1_out = src_buf4_V_6_reg_1296_pp0_iter10_reg;

assign src_buf4_V_2_out = src_buf4_V_7_reg_1302_pp0_iter10_reg;

assign src_buf4_V_out = src_buf4_V_5_reg_1290_pp0_iter10_reg;

assign src_buf5_V_0_out = src_buf5_V_4_fu_164;

assign src_buf5_V_1_out = src_buf5_V_6_reg_1314_pp0_iter10_reg;

assign src_buf5_V_2_out = src_buf5_V_7_reg_1320_pp0_iter10_reg;

assign src_buf5_V_out = src_buf5_V_5_reg_1308_pp0_iter10_reg;

assign tmp_fu_702_p4 = {{col_V_3_reg_1197[9:1]}};

assign zext_ln541_fu_694_p1 = col_V_3_reg_1197;

endmodule //accelerator_v2_xFGaussianFilter5x5_Pipeline_Col_Loop
