// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accelerator_v2_pad (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        bgr_stream1_dout,
        bgr_stream1_num_data_valid,
        bgr_stream1_fifo_cap,
        bgr_stream1_empty_n,
        bgr_stream1_read,
        padded_stream2_din,
        padded_stream2_num_data_valid,
        padded_stream2_fifo_cap,
        padded_stream2_full_n,
        padded_stream2_write
);

parameter    ap_ST_fsm_state1 = 29'd1;
parameter    ap_ST_fsm_state2 = 29'd2;
parameter    ap_ST_fsm_state3 = 29'd4;
parameter    ap_ST_fsm_state4 = 29'd8;
parameter    ap_ST_fsm_state5 = 29'd16;
parameter    ap_ST_fsm_state6 = 29'd32;
parameter    ap_ST_fsm_state7 = 29'd64;
parameter    ap_ST_fsm_state8 = 29'd128;
parameter    ap_ST_fsm_state9 = 29'd256;
parameter    ap_ST_fsm_state10 = 29'd512;
parameter    ap_ST_fsm_state11 = 29'd1024;
parameter    ap_ST_fsm_state12 = 29'd2048;
parameter    ap_ST_fsm_state13 = 29'd4096;
parameter    ap_ST_fsm_state14 = 29'd8192;
parameter    ap_ST_fsm_state15 = 29'd16384;
parameter    ap_ST_fsm_state16 = 29'd32768;
parameter    ap_ST_fsm_state17 = 29'd65536;
parameter    ap_ST_fsm_state18 = 29'd131072;
parameter    ap_ST_fsm_state19 = 29'd262144;
parameter    ap_ST_fsm_state20 = 29'd524288;
parameter    ap_ST_fsm_state21 = 29'd1048576;
parameter    ap_ST_fsm_state22 = 29'd2097152;
parameter    ap_ST_fsm_state23 = 29'd4194304;
parameter    ap_ST_fsm_state24 = 29'd8388608;
parameter    ap_ST_fsm_state25 = 29'd16777216;
parameter    ap_ST_fsm_state26 = 29'd33554432;
parameter    ap_ST_fsm_state27 = 29'd67108864;
parameter    ap_ST_fsm_state28 = 29'd134217728;
parameter    ap_ST_fsm_state29 = 29'd268435456;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] bgr_stream1_dout;
input  [19:0] bgr_stream1_num_data_valid;
input  [19:0] bgr_stream1_fifo_cap;
input   bgr_stream1_empty_n;
output   bgr_stream1_read;
output  [23:0] padded_stream2_din;
input  [19:0] padded_stream2_num_data_valid;
input  [19:0] padded_stream2_fifo_cap;
input   padded_stream2_full_n;
output   padded_stream2_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg bgr_stream1_read;
reg[23:0] padded_stream2_din;
reg padded_stream2_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [28:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    padded_stream2_blk_n;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln75_fu_380_p2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire   [0:0] icmp_ln111_fu_580_p2;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state3;
wire   [9:0] row_buf_V_2_addr_1_reg_683;
wire   [9:0] row_buf_V_2_addr_2_reg_688;
wire    ap_CS_fsm_state4;
wire   [9:0] row_buf_V_2_addr_reg_698;
wire   [23:0] row_buf_V_1_q1;
reg   [23:0] row_buf_V_1_load_reg_708;
wire   [23:0] row_buf_V_2_q1;
reg   [23:0] row_buf_V_2_load_reg_714;
wire   [23:0] row_buf_V_1_q0;
reg   [23:0] row_buf_V_1_load_1_reg_719;
wire   [23:0] row_buf_V_2_q0;
reg   [23:0] row_buf_V_2_load_1_reg_725;
wire   [9:0] row_buf_V_2_addr_3_reg_730;
reg   [23:0] row_buf_V_1_load_2_reg_735;
wire    ap_CS_fsm_state5;
reg   [23:0] row_buf_V_2_load_2_reg_741;
reg   [23:0] row_buf_V_1_load_3_reg_746;
reg   [23:0] row_buf_V_2_load_3_reg_752;
reg   [1:0] r_3_reg_757;
wire   [23:0] tmp_1_fu_423_p5;
reg   [23:0] tmp_1_reg_833;
wire    ap_CS_fsm_state8;
wire   [23:0] tmp_2_fu_432_p5;
reg   [23:0] tmp_2_reg_838;
wire    ap_CS_fsm_state12;
wire   [23:0] row_buf_V_q1;
reg   [23:0] row_buf_V_load_reg_848;
wire   [23:0] row_buf_V_q0;
reg   [23:0] row_buf_V_load_1_reg_853;
wire    ap_CS_fsm_state13;
reg   [23:0] row_buf_V_load_2_reg_878;
reg   [23:0] row_buf_V_load_3_reg_888;
wire   [8:0] r_9_fu_450_p2;
reg   [8:0] r_9_reg_896;
wire    ap_CS_fsm_state14;
wire   [1:0] trunc_ln87_fu_456_p1;
wire   [0:0] icmp_ln87_fu_444_p2;
wire   [0:0] trunc_ln87_1_fu_460_p1;
reg   [0:0] trunc_ln87_1_reg_906;
wire   [0:0] icmp_ln89_fu_465_p2;
reg   [0:0] icmp_ln89_reg_912;
wire   [1:0] slot_1_fu_476_p3;
wire    ap_CS_fsm_state16;
wire   [23:0] tmp_3_fu_500_p6;
reg   [23:0] tmp_3_reg_928;
wire   [23:0] tmp_10_fu_545_p6;
reg   [23:0] tmp_10_reg_933;
wire   [0:0] empty_89_fu_592_p1;
reg   [0:0] empty_89_reg_941;
reg   [9:0] row_buf_V_address0;
reg    row_buf_V_ce0;
reg    row_buf_V_we0;
reg   [9:0] row_buf_V_address1;
reg    row_buf_V_ce1;
reg   [9:0] row_buf_V_1_address0;
reg    row_buf_V_1_ce0;
reg    row_buf_V_1_we0;
reg   [9:0] row_buf_V_1_address1;
reg    row_buf_V_1_ce1;
reg   [9:0] row_buf_V_2_address0;
reg    row_buf_V_2_ce0;
reg    row_buf_V_2_we0;
reg   [23:0] row_buf_V_2_d0;
reg   [9:0] row_buf_V_2_address1;
reg    row_buf_V_2_ce1;
reg   [9:0] row_buf_V_3_address0;
reg    row_buf_V_3_ce0;
reg    row_buf_V_3_we0;
wire   [23:0] row_buf_V_3_q0;
reg   [9:0] row_buf_V_3_address1;
reg    row_buf_V_3_ce1;
wire   [23:0] row_buf_V_3_q1;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_done;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_idle;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_ready;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_bgr_stream1_read;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_we0;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_d0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_we0;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_d0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_we0;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_d0;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_done;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_idle;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_ready;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_padded_stream2_din;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_padded_stream2_write;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_1_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_1_ce0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_2_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_2_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_done;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_idle;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_ready;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_bgr_stream1_read;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_we0;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_d0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_we0;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_d0;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_done;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_idle;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_ready;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_padded_stream2_din;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_padded_stream2_write;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_ce0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_1_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_1_ce0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_2_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_2_ce0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_3_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_3_ce0;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_done;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_idle;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_ready;
wire   [23:0] grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_din;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_write;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_2_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_2_ce0;
wire   [9:0] grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_3_address0;
wire    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_3_ce0;
reg   [1:0] slot_reg_311;
reg    grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start_reg;
reg    ap_block_state1_ignore_call8;
wire    ap_CS_fsm_state2;
reg    grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg    grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start_reg;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
reg   [1:0] r_2_fu_84;
wire   [1:0] add_ln75_fu_397_p2;
reg    ap_block_state6;
reg    ap_block_state1;
reg   [23:0] mux_case_3130_phi_fu_104;
reg   [23:0] mux_case_2129_phi_fu_108;
reg   [23:0] mux_case_3_phi_fu_112;
reg   [23:0] mux_case_2126_phi_fu_116;
reg   [23:0] mux_case_3142_phi_fu_120;
reg   [23:0] mux_case_2141_phi_fu_124;
reg   [23:0] mux_case_3138_phi_fu_128;
reg   [23:0] mux_case_2137_phi_fu_132;
reg   [8:0] r_fu_136;
reg   [6:0] r_4_fu_140;
wire   [6:0] r_8_fu_607_p2;
reg    ap_block_state24;
wire   [23:0] tmp_fu_386_p5;
wire   [23:0] tmp_s_fu_413_p5;
wire   [23:0] tmp_9_fu_487_p6;
wire   [23:0] tmp_8_fu_532_p6;
wire   [23:0] tmp_4_fu_596_p4;
wire   [23:0] tmp_5_fu_624_p4;
wire   [23:0] tmp_6_fu_640_p4;
wire   [23:0] tmp_7_fu_656_p4;
wire    ap_CS_fsm_state21;
wire   [0:0] tmp_4_fu_596_p3;
reg   [28:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 29'd1;
#0 grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start_reg = 1'b0;
#0 grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start_reg = 1'b0;
#0 grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start_reg = 1'b0;
#0 grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start_reg = 1'b0;
#0 grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start_reg = 1'b0;
end

accelerator_v2_pad_row_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
row_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(row_buf_V_address0),
    .ce0(row_buf_V_ce0),
    .we0(row_buf_V_we0),
    .d0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_d0),
    .q0(row_buf_V_q0),
    .address1(row_buf_V_address1),
    .ce1(row_buf_V_ce1),
    .q1(row_buf_V_q1)
);

accelerator_v2_pad_row_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
row_buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(row_buf_V_1_address0),
    .ce0(row_buf_V_1_ce0),
    .we0(row_buf_V_1_we0),
    .d0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_d0),
    .q0(row_buf_V_1_q0),
    .address1(row_buf_V_1_address1),
    .ce1(row_buf_V_1_ce1),
    .q1(row_buf_V_1_q1)
);

accelerator_v2_pad_row_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
row_buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(row_buf_V_2_address0),
    .ce0(row_buf_V_2_ce0),
    .we0(row_buf_V_2_we0),
    .d0(row_buf_V_2_d0),
    .q0(row_buf_V_2_q0),
    .address1(row_buf_V_2_address1),
    .ce1(row_buf_V_2_ce1),
    .q1(row_buf_V_2_q1)
);

accelerator_v2_pad_row_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
row_buf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(row_buf_V_3_address0),
    .ce0(row_buf_V_3_ce0),
    .we0(row_buf_V_3_we0),
    .d0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_d0),
    .q0(row_buf_V_3_q0),
    .address1(row_buf_V_3_address1),
    .ce1(row_buf_V_3_ce1),
    .q1(row_buf_V_3_q1)
);

accelerator_v2_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2 grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start),
    .ap_done(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_done),
    .ap_idle(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_idle),
    .ap_ready(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_ready),
    .bgr_stream1_dout(bgr_stream1_dout),
    .bgr_stream1_num_data_valid(20'd0),
    .bgr_stream1_fifo_cap(20'd0),
    .bgr_stream1_empty_n(bgr_stream1_empty_n),
    .bgr_stream1_read(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_bgr_stream1_read),
    .row_buf_V_2_address0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_address0),
    .row_buf_V_2_ce0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_ce0),
    .row_buf_V_2_we0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_we0),
    .row_buf_V_2_d0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_d0),
    .row_buf_V_1_address0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_address0),
    .row_buf_V_1_ce0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_ce0),
    .row_buf_V_1_we0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_we0),
    .row_buf_V_1_d0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_d0),
    .row_buf_V_address0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_address0),
    .row_buf_V_ce0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_ce0),
    .row_buf_V_we0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_we0),
    .row_buf_V_d0(grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_d0)
);

accelerator_v2_pad_Pipeline_VITIS_LOOP_78_4 grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start),
    .ap_done(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_done),
    .ap_idle(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_idle),
    .ap_ready(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_ready),
    .padded_stream2_din(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_padded_stream2_din),
    .padded_stream2_num_data_valid(20'd0),
    .padded_stream2_fifo_cap(20'd0),
    .padded_stream2_full_n(padded_stream2_full_n),
    .padded_stream2_write(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_padded_stream2_write),
    .row_buf_V_1_address0(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_1_address0),
    .row_buf_V_1_ce0(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_1_ce0),
    .row_buf_V_1_q0(row_buf_V_1_q0),
    .row_buf_V_2_address0(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_2_address0),
    .row_buf_V_2_ce0(grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_2_ce0),
    .row_buf_V_2_q0(row_buf_V_2_q0),
    .r_2(r_3_reg_757)
);

accelerator_v2_pad_Pipeline_VITIS_LOOP_93_6 grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start),
    .ap_done(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_done),
    .ap_idle(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_idle),
    .ap_ready(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_ready),
    .bgr_stream1_dout(bgr_stream1_dout),
    .bgr_stream1_num_data_valid(20'd0),
    .bgr_stream1_fifo_cap(20'd0),
    .bgr_stream1_empty_n(bgr_stream1_empty_n),
    .bgr_stream1_read(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_bgr_stream1_read),
    .row_buf_V_3_address0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_address0),
    .row_buf_V_3_ce0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_ce0),
    .row_buf_V_3_we0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_we0),
    .row_buf_V_3_d0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_d0),
    .row_buf_V_2_address0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_address0),
    .row_buf_V_2_ce0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_ce0),
    .row_buf_V_2_we0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_we0),
    .row_buf_V_2_d0(grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_d0),
    .trunc_ln87_1(trunc_ln87_1_reg_906)
);

accelerator_v2_pad_Pipeline_VITIS_LOOP_101_7 grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start),
    .ap_done(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_done),
    .ap_idle(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_idle),
    .ap_ready(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_ready),
    .padded_stream2_din(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_padded_stream2_din),
    .padded_stream2_num_data_valid(20'd0),
    .padded_stream2_fifo_cap(20'd0),
    .padded_stream2_full_n(padded_stream2_full_n),
    .padded_stream2_write(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_padded_stream2_write),
    .row_buf_V_address0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_address0),
    .row_buf_V_ce0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_ce0),
    .row_buf_V_q0(row_buf_V_q0),
    .row_buf_V_1_address0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_1_address0),
    .row_buf_V_1_ce0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_1_ce0),
    .row_buf_V_1_q0(row_buf_V_1_q0),
    .row_buf_V_2_address0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_2_address0),
    .row_buf_V_2_ce0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_2_ce0),
    .row_buf_V_2_q0(row_buf_V_2_q0),
    .row_buf_V_3_address0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_3_address0),
    .row_buf_V_3_ce0(grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_3_ce0),
    .row_buf_V_3_q0(row_buf_V_3_q0),
    .slot(slot_reg_311)
);

accelerator_v2_pad_Pipeline_VITIS_LOOP_115_9 grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start),
    .ap_done(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_done),
    .ap_idle(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_idle),
    .ap_ready(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_ready),
    .padded_stream2_din(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_din),
    .padded_stream2_num_data_valid(20'd0),
    .padded_stream2_fifo_cap(20'd0),
    .padded_stream2_full_n(padded_stream2_full_n),
    .padded_stream2_write(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_write),
    .row_buf_V_2_address0(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_2_address0),
    .row_buf_V_2_ce0(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_2_ce0),
    .row_buf_V_2_q0(row_buf_V_2_q0),
    .row_buf_V_3_address0(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_3_address0),
    .row_buf_V_3_ce0(grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_3_ce0),
    .row_buf_V_3_q0(row_buf_V_3_q0),
    .r_5_cast(empty_89_reg_941)
);

accelerator_v2_mux_32_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_32_24_1_1_U65(
    .din0(24'd0),
    .din1(row_buf_V_1_load_reg_708),
    .din2(row_buf_V_2_load_reg_714),
    .din3(r_2_fu_84),
    .dout(tmp_fu_386_p5)
);

accelerator_v2_mux_32_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_32_24_1_1_U66(
    .din0(24'd0),
    .din1(row_buf_V_1_load_1_reg_719),
    .din2(row_buf_V_2_load_1_reg_725),
    .din3(r_3_reg_757),
    .dout(tmp_s_fu_413_p5)
);

accelerator_v2_mux_32_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_32_24_1_1_U67(
    .din0(24'd0),
    .din1(row_buf_V_1_load_2_reg_735),
    .din2(row_buf_V_2_load_2_reg_741),
    .din3(r_3_reg_757),
    .dout(tmp_1_fu_423_p5)
);

accelerator_v2_mux_32_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_32_24_1_1_U68(
    .din0(24'd0),
    .din1(row_buf_V_1_load_3_reg_746),
    .din2(row_buf_V_2_load_3_reg_752),
    .din3(r_3_reg_757),
    .dout(tmp_2_fu_432_p5)
);

accelerator_v2_mux_42_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 24 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_42_24_1_1_U69(
    .din0(row_buf_V_load_reg_848),
    .din1(row_buf_V_1_load_reg_708),
    .din2(row_buf_V_2_q1),
    .din3(row_buf_V_3_q1),
    .din4(slot_reg_311),
    .dout(tmp_9_fu_487_p6)
);

accelerator_v2_mux_42_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 24 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_42_24_1_1_U70(
    .din0(row_buf_V_load_1_reg_853),
    .din1(row_buf_V_1_load_1_reg_719),
    .din2(row_buf_V_2_q0),
    .din3(row_buf_V_3_q0),
    .din4(slot_reg_311),
    .dout(tmp_3_fu_500_p6)
);

accelerator_v2_mux_42_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 24 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_42_24_1_1_U71(
    .din0(row_buf_V_load_2_reg_878),
    .din1(row_buf_V_1_load_2_reg_735),
    .din2(row_buf_V_2_q1),
    .din3(row_buf_V_3_q1),
    .din4(slot_reg_311),
    .dout(tmp_8_fu_532_p6)
);

accelerator_v2_mux_42_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 24 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_42_24_1_1_U72(
    .din0(row_buf_V_load_3_reg_888),
    .din1(row_buf_V_1_load_3_reg_746),
    .din2(row_buf_V_2_q0),
    .din3(row_buf_V_3_q0),
    .din4(slot_reg_311),
    .dout(tmp_10_fu_545_p6)
);

accelerator_v2_mux_21_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 24 ))
mux_21_24_1_1_U73(
    .din0(mux_case_2126_phi_fu_116),
    .din1(mux_case_3_phi_fu_112),
    .din2(tmp_4_fu_596_p3),
    .dout(tmp_4_fu_596_p4)
);

accelerator_v2_mux_21_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 24 ))
mux_21_24_1_1_U74(
    .din0(mux_case_2129_phi_fu_108),
    .din1(mux_case_3130_phi_fu_104),
    .din2(empty_89_reg_941),
    .dout(tmp_5_fu_624_p4)
);

accelerator_v2_mux_21_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 24 ))
mux_21_24_1_1_U75(
    .din0(mux_case_2137_phi_fu_132),
    .din1(mux_case_3138_phi_fu_128),
    .din2(empty_89_reg_941),
    .dout(tmp_6_fu_640_p4)
);

accelerator_v2_mux_21_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 24 ))
mux_21_24_1_1_U76(
    .din0(mux_case_2141_phi_fu_124),
    .din1(mux_case_3142_phi_fu_120),
    .din2(empty_89_reg_941),
    .dout(tmp_7_fu_656_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start_reg <= 1'b1;
        end else if ((grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_ready == 1'b1)) begin
            grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state26)) begin
            grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start_reg <= 1'b1;
        end else if ((grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_ready == 1'b1)) begin
            grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start_reg <= 1'b1;
        end else if ((grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_ready == 1'b1)) begin
            grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start_reg <= 1'b1;
        end else if ((grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_ready == 1'b1)) begin
            grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln89_fu_465_p2 == 1'd0) & (icmp_ln87_fu_444_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start_reg <= 1'b1;
        end else if ((grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_ready == 1'b1)) begin
            grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        r_2_fu_84 <= 2'd2;
    end else if ((~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (icmp_ln75_fu_380_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        r_2_fu_84 <= add_ln75_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln87_fu_444_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        r_4_fu_140 <= 7'd94;
    end else if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd1))) begin
        r_4_fu_140 <= r_8_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (icmp_ln75_fu_380_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        r_fu_136 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        r_fu_136 <= r_9_reg_896;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln89_fu_465_p2 == 1'd1) & (icmp_ln87_fu_444_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        slot_reg_311 <= trunc_ln87_fu_456_p1;
    end else if (((icmp_ln89_reg_912 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        slot_reg_311 <= slot_1_fu_476_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd1))) begin
        empty_89_reg_941 <= empty_89_fu_592_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln87_fu_444_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        icmp_ln89_reg_912 <= icmp_ln89_fu_465_p2;
        trunc_ln87_1_reg_906 <= trunc_ln87_1_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        mux_case_2126_phi_fu_116 <= row_buf_V_2_q1;
        mux_case_2129_phi_fu_108 <= row_buf_V_2_q0;
        mux_case_3130_phi_fu_104 <= row_buf_V_3_q0;
        mux_case_3_phi_fu_112 <= row_buf_V_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        mux_case_2137_phi_fu_132 <= row_buf_V_2_q1;
        mux_case_2141_phi_fu_124 <= row_buf_V_2_q0;
        mux_case_3138_phi_fu_128 <= row_buf_V_3_q1;
        mux_case_3142_phi_fu_120 <= row_buf_V_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_3_reg_757 <= r_2_fu_84;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        r_9_reg_896 <= r_9_fu_450_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buf_V_1_load_1_reg_719 <= row_buf_V_1_q0;
        row_buf_V_1_load_reg_708 <= row_buf_V_1_q1;
        row_buf_V_2_load_1_reg_725 <= row_buf_V_2_q0;
        row_buf_V_2_load_reg_714 <= row_buf_V_2_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        row_buf_V_1_load_2_reg_735 <= row_buf_V_1_q1;
        row_buf_V_1_load_3_reg_746 <= row_buf_V_1_q0;
        row_buf_V_2_load_2_reg_741 <= row_buf_V_2_q1;
        row_buf_V_2_load_3_reg_752 <= row_buf_V_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        row_buf_V_load_1_reg_853 <= row_buf_V_q0;
        row_buf_V_load_reg_848 <= row_buf_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        row_buf_V_load_2_reg_878 <= row_buf_V_q1;
        row_buf_V_load_3_reg_888 <= row_buf_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        tmp_10_reg_933 <= tmp_10_fu_545_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_1_reg_833 <= tmp_1_fu_423_p5;
        tmp_2_reg_838 <= tmp_2_fu_432_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tmp_3_reg_928 <= tmp_3_fu_500_p6;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if (((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1))) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((padded_stream2_full_n == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        bgr_stream1_read = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_bgr_stream1_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        bgr_stream1_read = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_bgr_stream1_read;
    end else begin
        bgr_stream1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state11) | ((icmp_ln75_fu_380_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd1)))) begin
        padded_stream2_blk_n = padded_stream2_full_n;
    end else begin
        padded_stream2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        padded_stream2_din = tmp_7_fu_656_p4;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        padded_stream2_din = tmp_6_fu_640_p4;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        padded_stream2_din = tmp_5_fu_624_p4;
    end else if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd1))) begin
        padded_stream2_din = tmp_4_fu_596_p4;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        padded_stream2_din = tmp_10_reg_933;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        padded_stream2_din = tmp_8_fu_532_p6;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        padded_stream2_din = tmp_3_reg_928;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        padded_stream2_din = tmp_9_fu_487_p6;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        padded_stream2_din = tmp_2_reg_838;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        padded_stream2_din = tmp_1_reg_833;
    end else if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        padded_stream2_din = tmp_s_fu_413_p5;
    end else if ((~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (icmp_ln75_fu_380_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        padded_stream2_din = tmp_fu_386_p5;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        padded_stream2_din = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_din;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        padded_stream2_din = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_padded_stream2_din;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        padded_stream2_din = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_padded_stream2_din;
    end else begin
        padded_stream2_din = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_din;
    end
end

always @ (*) begin
    if (((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd1)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state28)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state23)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | (~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (icmp_ln75_fu_380_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)))) begin
        padded_stream2_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        padded_stream2_write = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_padded_stream2_write;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        padded_stream2_write = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_padded_stream2_write;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        padded_stream2_write = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_padded_stream2_write;
    end else begin
        padded_stream2_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buf_V_1_address0 = 64'd637;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        row_buf_V_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_1_address0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        row_buf_V_1_address0 = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_1_address0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_address0;
    end else begin
        row_buf_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buf_V_1_address1 = 64'd638;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        row_buf_V_1_address1 = 64'd2;
    end else begin
        row_buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        row_buf_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_1_ce0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        row_buf_V_1_ce0 = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_1_ce0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_ce0;
    end else begin
        row_buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        row_buf_V_1_ce1 = 1'b1;
    end else begin
        row_buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_1_we0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_1_we0;
    end else begin
        row_buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        row_buf_V_2_address0 = row_buf_V_2_addr_3_reg_730;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        row_buf_V_2_address0 = row_buf_V_2_addr_2_reg_688;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buf_V_2_address0 = 64'd637;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        row_buf_V_2_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        row_buf_V_2_address0 = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_2_address0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_2_address0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        row_buf_V_2_address0 = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_2_address0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_address0;
    end else begin
        row_buf_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        row_buf_V_2_address1 = row_buf_V_2_addr_reg_698;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        row_buf_V_2_address1 = row_buf_V_2_addr_1_reg_683;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        row_buf_V_2_address1 = 64'd638;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        row_buf_V_2_address1 = 64'd2;
    end else begin
        row_buf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        row_buf_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        row_buf_V_2_ce0 = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_2_ce0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_2_ce0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        row_buf_V_2_ce0 = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_row_buf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_2_ce0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_ce0;
    end else begin
        row_buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        row_buf_V_2_ce1 = 1'b1;
    end else begin
        row_buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_2_d0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_2_d0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_d0;
    end else begin
        row_buf_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_2_we0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_2_we0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_2_we0;
    end else begin
        row_buf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        row_buf_V_3_address0 = 64'd637;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        row_buf_V_3_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        row_buf_V_3_address0 = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_3_address0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_3_address0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_address0;
    end else begin
        row_buf_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        row_buf_V_3_address1 = 64'd638;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        row_buf_V_3_address1 = 64'd2;
    end else begin
        row_buf_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state16))) begin
        row_buf_V_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        row_buf_V_3_ce0 = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_row_buf_V_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_3_ce0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_3_ce0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_ce0;
    end else begin
        row_buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state16))) begin
        row_buf_V_3_ce1 = 1'b1;
    end else begin
        row_buf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        row_buf_V_3_we0 = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_row_buf_V_3_we0;
    end else begin
        row_buf_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        row_buf_V_address0 = 64'd637;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buf_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_address0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_address0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_address0;
    end else begin
        row_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        row_buf_V_address1 = 64'd638;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        row_buf_V_address1 = 64'd2;
    end else begin
        row_buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)))) begin
        row_buf_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        row_buf_V_ce0 = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_row_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_ce0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_ce0;
    end else begin
        row_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)))) begin
        row_buf_V_ce1 = 1'b1;
    end else begin
        row_buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_buf_V_we0 = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_row_buf_V_we0;
    end else begin
        row_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if ((~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (icmp_ln75_fu_380_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if ((~((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0)) & (icmp_ln75_fu_380_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln87_fu_444_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((icmp_ln89_fu_465_p2 == 1'd1) & (icmp_ln87_fu_444_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state24) & (icmp_ln111_fu_580_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((padded_stream2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln75_fu_397_p2 = ($signed(r_2_fu_84) + $signed(2'd3));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call8 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state24 = ((padded_stream2_full_n == 1'b0) & (icmp_ln111_fu_580_p2 == 1'd1));
end

always @ (*) begin
    ap_block_state6 = ((icmp_ln75_fu_380_p2 == 1'd0) & (padded_stream2_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign empty_89_fu_592_p1 = r_4_fu_140[0:0];

assign grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start = grp_pad_Pipeline_VITIS_LOOP_101_7_fu_351_ap_start_reg;

assign grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start = grp_pad_Pipeline_VITIS_LOOP_115_9_fu_363_ap_start_reg;

assign grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start = grp_pad_Pipeline_VITIS_LOOP_66_1_VITIS_LOOP_67_2_fu_321_ap_start_reg;

assign grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start = grp_pad_Pipeline_VITIS_LOOP_78_4_fu_333_ap_start_reg;

assign grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start = grp_pad_Pipeline_VITIS_LOOP_93_6_fu_342_ap_start_reg;

assign icmp_ln111_fu_580_p2 = ((r_4_fu_140 > 7'd92) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_380_p2 = ((r_2_fu_84 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_444_p2 = ((r_fu_136 == 9'd480) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_465_p2 = ((r_fu_136 < 9'd3) ? 1'b1 : 1'b0);

assign r_8_fu_607_p2 = ($signed(r_4_fu_140) + $signed(7'd127));

assign r_9_fu_450_p2 = (r_fu_136 + 9'd1);

assign row_buf_V_2_addr_1_reg_683 = 64'd2;

assign row_buf_V_2_addr_2_reg_688 = 64'd1;

assign row_buf_V_2_addr_3_reg_730 = 64'd637;

assign row_buf_V_2_addr_reg_698 = 64'd638;

assign slot_1_fu_476_p3 = {{1'd1}, {trunc_ln87_1_reg_906}};

assign start_out = real_start;

assign tmp_4_fu_596_p3 = r_4_fu_140[0:0];

assign trunc_ln87_1_fu_460_p1 = r_fu_136[0:0];

assign trunc_ln87_fu_456_p1 = r_fu_136[1:0];

endmodule //accelerator_v2_pad
