// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_passthrough_xFapplygaussian3x3_0_s (
        ap_clk,
        ap_rst,
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9,
        p_read1,
        p_read2,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [0:0] D1;
input  [0:0] D2;
input  [7:0] D3;
input  [0:0] D4;
input  [0:0] D5;
input  [7:0] D6;
input  [0:0] D7;
input  [0:0] D8;
input  [7:0] D9;
input  [7:0] p_read1;
input  [7:0] p_read2;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

reg   [7:0] p_read_reg_250;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] p_read_reg_250_pp0_iter1_reg;
reg   [7:0] p_read_reg_250_pp0_iter2_reg;
reg   [7:0] p_read_reg_250_pp0_iter3_reg;
reg   [7:0] p_read_10_reg_257;
reg   [7:0] p_read_10_reg_257_pp0_iter1_reg;
reg   [7:0] p_read_10_reg_257_pp0_iter2_reg;
reg   [0:0] D8_read_reg_263;
reg   [0:0] D8_read_reg_263_pp0_iter1_reg;
reg   [0:0] D8_read_reg_263_pp0_iter2_reg;
reg   [7:0] D6_read_reg_268;
reg   [0:0] D5_read_reg_273;
reg   [0:0] D5_read_reg_273_pp0_iter1_reg;
reg   [0:0] D5_read_reg_273_pp0_iter2_reg;
reg   [0:0] D5_read_reg_273_pp0_iter3_reg;
reg   [0:0] D4_read_reg_278;
reg   [0:0] D2_read_reg_283;
reg   [0:0] D2_read_reg_283_pp0_iter1_reg;
reg   [0:0] D2_read_reg_283_pp0_iter2_reg;
wire   [23:0] grp_fu_229_p4;
wire    ap_block_pp0_stage0;
wire   [1:0] zext_ln1495_3_fu_104_p1;
wire   [1:0] zext_ln1495_11_fu_112_p1;
wire   [1:0] add_ln1495_fu_116_p2;
wire   [8:0] zext_ln1495_12_fu_122_p1;
wire   [8:0] zext_ln186_2_fu_108_p1;
wire   [8:0] ret_V_12_fu_126_p2;
wire   [1:0] zext_ln1495_7_fu_156_p1;
wire   [1:0] zext_ln1495_6_fu_153_p1;
wire   [1:0] ret_V_14_fu_159_p2;
wire   [7:0] ret_V_15_fu_172_p0;
wire   [1:0] ret_V_15_fu_172_p1;
wire   [9:0] ret_V_15_fu_172_p2;
wire   [7:0] select_ln1494_fu_185_p3;
wire   [7:0] ret_V_10_fu_192_p2;
wire   [23:0] grp_fu_239_p4;
wire   [8:0] grp_fu_213_p0;
wire   [7:0] grp_fu_213_p1;
wire   [7:0] grp_fu_213_p2;
wire   [7:0] grp_fu_221_p0;
wire   [0:0] grp_fu_221_p1;
wire   [7:0] grp_fu_221_p2;
wire   [16:0] grp_fu_213_p3;
wire   [9:0] grp_fu_229_p1;
wire   [7:0] grp_fu_229_p2;
wire   [15:0] grp_fu_229_p3;
wire   [15:0] grp_fu_221_p3;
wire   [7:0] grp_fu_239_p1;
wire   [7:0] grp_fu_239_p2;
reg    grp_fu_213_ce;
reg    grp_fu_221_ce;
reg    grp_fu_229_ce;
reg    grp_fu_239_ce;
reg    ap_ce_reg;
reg   [0:0] D1_int_reg;
reg   [0:0] D2_int_reg;
reg   [7:0] D3_int_reg;
reg   [0:0] D4_int_reg;
reg   [0:0] D5_int_reg;
reg   [7:0] D6_int_reg;
reg   [0:0] D7_int_reg;
reg   [0:0] D8_int_reg;
reg   [7:0] D9_int_reg;
reg   [7:0] p_read1_int_reg;
reg   [7:0] p_read2_int_reg;
reg   [7:0] ap_return_int_reg;
wire   [9:0] grp_fu_213_p00;
wire   [9:0] grp_fu_213_p10;
wire   [16:0] grp_fu_213_p20;
wire   [8:0] grp_fu_221_p00;
wire   [8:0] grp_fu_221_p10;
wire   [15:0] grp_fu_221_p20;
wire   [16:0] grp_fu_229_p10;
wire   [23:0] grp_fu_229_p20;
wire   [15:0] grp_fu_239_p10;
wire   [23:0] grp_fu_239_p20;
wire   [9:0] ret_V_15_fu_172_p00;
wire   [9:0] ret_V_15_fu_172_p10;

image_passthrough_mul_8ns_2ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mul_8ns_2ns_10_1_0_U112(
    .din0(ret_V_15_fu_172_p0),
    .din1(ret_V_15_fu_172_p1),
    .dout(ret_V_15_fu_172_p2)
);

image_passthrough_am_addmul_9ns_8ns_8ns_17_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 17 ))
am_addmul_9ns_8ns_8ns_17_4_0_U113(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_213_p0),
    .din1(grp_fu_213_p1),
    .din2(grp_fu_213_p2),
    .ce(grp_fu_213_ce),
    .dout(grp_fu_213_p3)
);

image_passthrough_am_addmul_8ns_1ns_8ns_16_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
am_addmul_8ns_1ns_8ns_16_4_0_U114(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_221_p0),
    .din1(grp_fu_221_p1),
    .din2(grp_fu_221_p2),
    .ce(grp_fu_221_ce),
    .dout(grp_fu_221_p3)
);

image_passthrough_ama_addmuladd_17ns_10ns_8ns_16ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
ama_addmuladd_17ns_10ns_8ns_16ns_24_4_0_U115(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_213_p3),
    .din1(grp_fu_229_p1),
    .din2(grp_fu_229_p2),
    .din3(grp_fu_229_p3),
    .ce(grp_fu_229_ce),
    .dout(grp_fu_229_p4)
);

image_passthrough_ama_addmuladd_16ns_8ns_8ns_24ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
ama_addmuladd_16ns_8ns_8ns_24ns_24_4_0_U116(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_221_p3),
    .din1(grp_fu_239_p1),
    .din2(grp_fu_239_p2),
    .din3(grp_fu_229_p4),
    .ce(grp_fu_239_ce),
    .dout(grp_fu_239_p4)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        D1_int_reg <= D1;
        D2_int_reg <= D2;
        D3_int_reg <= D3;
        D4_int_reg <= D4;
        D5_int_reg <= D5;
        D6_int_reg <= D6;
        D7_int_reg <= D7;
        D8_int_reg <= D8;
        D9_int_reg <= D9;
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        D2_read_reg_283 <= D2_int_reg;
        D2_read_reg_283_pp0_iter1_reg <= D2_read_reg_283;
        D2_read_reg_283_pp0_iter2_reg <= D2_read_reg_283_pp0_iter1_reg;
        D4_read_reg_278 <= D4_int_reg;
        D5_read_reg_273 <= D5_int_reg;
        D5_read_reg_273_pp0_iter1_reg <= D5_read_reg_273;
        D5_read_reg_273_pp0_iter2_reg <= D5_read_reg_273_pp0_iter1_reg;
        D5_read_reg_273_pp0_iter3_reg <= D5_read_reg_273_pp0_iter2_reg;
        D6_read_reg_268 <= D6_int_reg;
        D8_read_reg_263 <= D8_int_reg;
        D8_read_reg_263_pp0_iter1_reg <= D8_read_reg_263;
        D8_read_reg_263_pp0_iter2_reg <= D8_read_reg_263_pp0_iter1_reg;
        p_read_10_reg_257 <= p_read1_int_reg;
        p_read_10_reg_257_pp0_iter1_reg <= p_read_10_reg_257;
        p_read_10_reg_257_pp0_iter2_reg <= p_read_10_reg_257_pp0_iter1_reg;
        p_read_reg_250 <= p_read2_int_reg;
        p_read_reg_250_pp0_iter1_reg <= p_read_reg_250;
        p_read_reg_250_pp0_iter2_reg <= p_read_reg_250_pp0_iter1_reg;
        p_read_reg_250_pp0_iter3_reg <= p_read_reg_250_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= {{grp_fu_239_p4[23:16]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = {{grp_fu_239_p4[23:16]}};
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_213_ce = 1'b1;
    end else begin
        grp_fu_213_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_221_ce = 1'b1;
    end else begin
        grp_fu_221_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_229_ce = 1'b1;
    end else begin
        grp_fu_229_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_239_ce = 1'b1;
    end else begin
        grp_fu_239_ce = 1'b0;
    end
end

assign add_ln1495_fu_116_p2 = (zext_ln1495_3_fu_104_p1 + zext_ln1495_11_fu_112_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign grp_fu_213_p0 = grp_fu_213_p00;

assign grp_fu_213_p00 = ret_V_12_fu_126_p2;

assign grp_fu_213_p1 = grp_fu_213_p10;

assign grp_fu_213_p10 = D9_int_reg;

assign grp_fu_213_p2 = grp_fu_213_p20;

assign grp_fu_213_p20 = p_read1_int_reg;

assign grp_fu_221_p0 = grp_fu_221_p00;

assign grp_fu_221_p00 = D6_read_reg_268;

assign grp_fu_221_p1 = grp_fu_221_p10;

assign grp_fu_221_p10 = D4_read_reg_278;

assign grp_fu_221_p2 = grp_fu_221_p20;

assign grp_fu_221_p20 = p_read_10_reg_257;

assign grp_fu_229_p1 = grp_fu_229_p10;

assign grp_fu_229_p10 = ret_V_15_fu_172_p2;

assign grp_fu_229_p2 = grp_fu_229_p20;

assign grp_fu_229_p20 = p_read_10_reg_257_pp0_iter2_reg;

assign grp_fu_229_p3 = 24'd32768;

assign grp_fu_239_p1 = grp_fu_239_p10;

assign grp_fu_239_p10 = ret_V_10_fu_192_p2;

assign grp_fu_239_p2 = grp_fu_239_p20;

assign grp_fu_239_p20 = p_read_reg_250_pp0_iter3_reg;

assign ret_V_10_fu_192_p2 = (select_ln1494_fu_185_p3 & p_read_reg_250_pp0_iter3_reg);

assign ret_V_12_fu_126_p2 = (zext_ln1495_12_fu_122_p1 + zext_ln186_2_fu_108_p1);

assign ret_V_14_fu_159_p2 = (zext_ln1495_7_fu_156_p1 + zext_ln1495_6_fu_153_p1);

assign ret_V_15_fu_172_p0 = ret_V_15_fu_172_p00;

assign ret_V_15_fu_172_p00 = p_read_reg_250_pp0_iter2_reg;

assign ret_V_15_fu_172_p1 = ret_V_15_fu_172_p10;

assign ret_V_15_fu_172_p10 = ret_V_14_fu_159_p2;

assign select_ln1494_fu_185_p3 = ((D5_read_reg_273_pp0_iter3_reg[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign zext_ln1495_11_fu_112_p1 = D7_int_reg;

assign zext_ln1495_12_fu_122_p1 = add_ln1495_fu_116_p2;

assign zext_ln1495_3_fu_104_p1 = D1_int_reg;

assign zext_ln1495_6_fu_153_p1 = D2_read_reg_283_pp0_iter2_reg;

assign zext_ln1495_7_fu_156_p1 = D8_read_reg_263_pp0_iter2_reg;

assign zext_ln186_2_fu_108_p1 = D3_int_reg;

endmodule //image_passthrough_xFapplygaussian3x3_0_s
