// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accelerator_v2_unpack_Pipeline_VITIS_LOOP_48_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        bgr_stream1_din,
        bgr_stream1_num_data_valid,
        bgr_stream1_fifo_cap,
        bgr_stream1_full_n,
        bgr_stream1_write,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
output  [23:0] bgr_stream1_din;
input  [12:0] bgr_stream1_num_data_valid;
input  [12:0] bgr_stream1_fifo_cap;
input   bgr_stream1_full_n;
output   bgr_stream1_write;
input  [127:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [15:0] in_stream_TKEEP;
input  [15:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;

reg ap_idle;
reg bgr_stream1_write;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln48_fu_143_p2;
wire   [0:0] icmp_ln51_fu_159_p2;
reg    ap_predicate_op29_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] trunc_ln55_reg_304;
reg    ap_predicate_op53_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    bgr_stream1_blk_n;
wire   [3:0] trunc_ln48_fu_155_p1;
reg   [3:0] trunc_ln48_reg_296;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln55_fu_174_p1;
reg   [10:0] lane_fu_72;
wire   [10:0] select_ln46_fu_190_p3;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_lane_1;
reg   [10:0] byte_idx_fu_76;
wire   [10:0] byte_idx_2_fu_149_p2;
reg   [10:0] ap_sig_allocacmp_byte_idx_1;
reg   [7:0] carry_b_V_fu_80;
wire   [7:0] carry_b_V_2_fu_228_p1;
reg   [7:0] carry_g_V_fu_84;
reg   [127:0] cur_burst_data_V_fu_88;
reg    ap_block_pp0_stage0_01001;
wire   [10:0] add_ln46_fu_178_p2;
wire   [0:0] icmp_ln46_fu_184_p2;
wire   [6:0] shl_ln_fu_211_p3;
wire   [127:0] zext_ln628_fu_218_p1;
wire   [127:0] lshr_ln628_fu_222_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

accelerator_v2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_143_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            byte_idx_fu_76 <= byte_idx_2_fu_149_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            byte_idx_fu_76 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            carry_b_V_fu_80 <= 8'd0;
        end else if (((trunc_ln55_reg_304 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            carry_b_V_fu_80 <= carry_b_V_2_fu_228_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            carry_g_V_fu_84 <= 8'd0;
        end else if (((trunc_ln55_reg_304 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            carry_g_V_fu_84 <= carry_b_V_2_fu_228_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln48_fu_143_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            lane_fu_72 <= select_ln46_fu_190_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            lane_fu_72 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln51_fu_159_p2 == 1'd1) & (icmp_ln48_fu_143_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_burst_data_V_fu_88 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln48_fu_143_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln48_reg_296 <= trunc_ln48_fu_155_p1;
        trunc_ln55_reg_304 <= trunc_ln55_fu_174_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln48_fu_143_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_byte_idx_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_byte_idx_1 = byte_idx_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_lane_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_lane_1 = lane_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op53_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bgr_stream1_blk_n = bgr_stream1_full_n;
    end else begin
        bgr_stream1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op53_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bgr_stream1_write = 1'b1;
    end else begin
        bgr_stream1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op29_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op29_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_fu_178_p2 = (ap_sig_allocacmp_lane_1 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op53_write_state2 == 1'b1) & (bgr_stream1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_predicate_op29_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_predicate_op53_write_state2 == 1'b1) & (bgr_stream1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_predicate_op29_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_predicate_op53_write_state2 == 1'b1) & (bgr_stream1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_predicate_op29_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op29_read_state1 == 1'b1) & (in_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op53_write_state2 == 1'b1) & (bgr_stream1_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op29_read_state1 = ((icmp_ln51_fu_159_p2 == 1'd1) & (icmp_ln48_fu_143_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op53_write_state2 = (~(trunc_ln55_reg_304 == 2'd1) & ~(trunc_ln55_reg_304 == 2'd0));
end

assign bgr_stream1_din = {{{carry_b_V_2_fu_228_p1}, {carry_g_V_fu_84}}, {carry_b_V_fu_80}};

assign byte_idx_2_fu_149_p2 = (ap_sig_allocacmp_byte_idx_1 + 11'd1);

assign carry_b_V_2_fu_228_p1 = lshr_ln628_fu_222_p2[7:0];

assign icmp_ln46_fu_184_p2 = ((add_ln46_fu_178_p2 < 11'd3) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_143_p2 = ((ap_sig_allocacmp_byte_idx_1 == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_159_p2 = ((trunc_ln48_fu_155_p1 == 4'd0) ? 1'b1 : 1'b0);

assign lshr_ln628_fu_222_p2 = cur_burst_data_V_fu_88 >> zext_ln628_fu_218_p1;

assign select_ln46_fu_190_p3 = ((icmp_ln46_fu_184_p2[0:0] == 1'b1) ? add_ln46_fu_178_p2 : 11'd0);

assign shl_ln_fu_211_p3 = {{trunc_ln48_reg_296}, {3'd0}};

assign trunc_ln48_fu_155_p1 = ap_sig_allocacmp_byte_idx_1[3:0];

assign trunc_ln55_fu_174_p1 = ap_sig_allocacmp_lane_1[1:0];

assign zext_ln628_fu_218_p1 = shl_ln_fu_211_p3;

endmodule //accelerator_v2_unpack_Pipeline_VITIS_LOOP_48_2
