-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accelerator_v2_repack_Pipeline_VITIS_LOOP_211_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    row_pixels_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce0 : OUT STD_LOGIC;
    row_pixels_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce1 : OUT STD_LOGIC;
    row_pixels_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address2 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce2 : OUT STD_LOGIC;
    row_pixels_V_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address3 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce3 : OUT STD_LOGIC;
    row_pixels_V_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address4 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce4 : OUT STD_LOGIC;
    row_pixels_V_q4 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address5 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce5 : OUT STD_LOGIC;
    row_pixels_V_q5 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address6 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce6 : OUT STD_LOGIC;
    row_pixels_V_q6 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address7 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce7 : OUT STD_LOGIC;
    row_pixels_V_q7 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address8 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce8 : OUT STD_LOGIC;
    row_pixels_V_q8 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address9 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce9 : OUT STD_LOGIC;
    row_pixels_V_q9 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address10 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce10 : OUT STD_LOGIC;
    row_pixels_V_q10 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address11 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce11 : OUT STD_LOGIC;
    row_pixels_V_q11 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address12 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce12 : OUT STD_LOGIC;
    row_pixels_V_q12 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address13 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce13 : OUT STD_LOGIC;
    row_pixels_V_q13 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_address14 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_ce14 : OUT STD_LOGIC;
    row_pixels_V_q14 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce0 : OUT STD_LOGIC;
    row_pixels_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce1 : OUT STD_LOGIC;
    row_pixels_V_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address2 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce2 : OUT STD_LOGIC;
    row_pixels_V_1_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address3 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce3 : OUT STD_LOGIC;
    row_pixels_V_1_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address4 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce4 : OUT STD_LOGIC;
    row_pixels_V_1_q4 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address5 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce5 : OUT STD_LOGIC;
    row_pixels_V_1_q5 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address6 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce6 : OUT STD_LOGIC;
    row_pixels_V_1_q6 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address7 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce7 : OUT STD_LOGIC;
    row_pixels_V_1_q7 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address8 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce8 : OUT STD_LOGIC;
    row_pixels_V_1_q8 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address9 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce9 : OUT STD_LOGIC;
    row_pixels_V_1_q9 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address10 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce10 : OUT STD_LOGIC;
    row_pixels_V_1_q10 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address11 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce11 : OUT STD_LOGIC;
    row_pixels_V_1_q11 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address12 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce12 : OUT STD_LOGIC;
    row_pixels_V_1_q12 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address13 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce13 : OUT STD_LOGIC;
    row_pixels_V_1_q13 : IN STD_LOGIC_VECTOR (7 downto 0);
    row_pixels_V_1_address14 : OUT STD_LOGIC_VECTOR (8 downto 0);
    row_pixels_V_1_ce14 : OUT STD_LOGIC;
    row_pixels_V_1_q14 : IN STD_LOGIC_VECTOR (7 downto 0);
    cmp39 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp43 : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of accelerator_v2_repack_Pipeline_VITIS_LOOP_211_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv10_5 : STD_LOGIC_VECTOR (9 downto 0) := "0000000101";
    constant ap_const_lv9_3 : STD_LOGIC_VECTOR (8 downto 0) := "000000011";
    constant ap_const_lv10_7 : STD_LOGIC_VECTOR (9 downto 0) := "0000000111";
    constant ap_const_lv9_4 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_const_lv10_9 : STD_LOGIC_VECTOR (9 downto 0) := "0000001001";
    constant ap_const_lv9_5 : STD_LOGIC_VECTOR (8 downto 0) := "000000101";
    constant ap_const_lv10_B : STD_LOGIC_VECTOR (9 downto 0) := "0000001011";
    constant ap_const_lv9_6 : STD_LOGIC_VECTOR (8 downto 0) := "000000110";
    constant ap_const_lv10_D : STD_LOGIC_VECTOR (9 downto 0) := "0000001101";
    constant ap_const_lv9_7 : STD_LOGIC_VECTOR (8 downto 0) := "000000111";
    constant ap_const_lv10_F : STD_LOGIC_VECTOR (9 downto 0) := "0000001111";
    constant ap_const_lv9_8 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln211_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ob_reg_1113 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln223_fu_581_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_1_fu_603_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_2_fu_615_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_3_fu_637_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_4_fu_649_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_5_fu_671_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_6_fu_683_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_7_fu_705_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_8_fu_717_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_9_fu_739_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_10_fu_751_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_11_fu_773_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_12_fu_785_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_13_fu_807_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_14_fu_819_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ob_1_fu_120 : STD_LOGIC_VECTOR (5 downto 0);
    signal ob_2_fu_541_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_ob : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_shl_fu_551_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln211_fu_547_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_fu_559_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln223_1_fu_565_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_fu_575_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_1_fu_587_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_1_fu_593_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_2_fu_609_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_3_fu_621_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_2_fu_627_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_4_fu_643_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_5_fu_655_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_3_fu_661_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_6_fu_677_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_7_fu_689_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_4_fu_695_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_8_fu_711_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_9_fu_723_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_5_fu_729_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_10_fu_745_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_11_fu_757_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_6_fu_763_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_12_fu_779_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_13_fu_791_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln223_7_fu_797_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_14_fu_813_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln223_fu_835_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal gray_V_fu_838_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_1_fu_848_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_2_fu_858_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_3_fu_868_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_4_fu_878_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_5_fu_888_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_6_fu_898_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_7_fu_908_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_8_fu_918_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_9_fu_928_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_10_fu_964_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_11_fu_974_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_12_fu_984_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_13_fu_994_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_V_14_fu_1004_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln218_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_1014_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Result_s_fu_938_p12 : STD_LOGIC_VECTOR (127 downto 0);
    signal out_burst_data_V_1_fu_1050_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln214_fu_1058_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln231_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln232_fu_1085_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component accelerator_v2_mux_21_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component accelerator_v2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_21_8_1_1_U224 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q14,
        din1 => row_pixels_V_1_q14,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_fu_838_p4);

    mux_21_8_1_1_U225 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q13,
        din1 => row_pixels_V_q13,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_1_fu_848_p4);

    mux_21_8_1_1_U226 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q12,
        din1 => row_pixels_V_1_q12,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_2_fu_858_p4);

    mux_21_8_1_1_U227 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q11,
        din1 => row_pixels_V_q11,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_3_fu_868_p4);

    mux_21_8_1_1_U228 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q10,
        din1 => row_pixels_V_1_q10,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_4_fu_878_p4);

    mux_21_8_1_1_U229 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q9,
        din1 => row_pixels_V_q9,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_5_fu_888_p4);

    mux_21_8_1_1_U230 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q8,
        din1 => row_pixels_V_1_q8,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_6_fu_898_p4);

    mux_21_8_1_1_U231 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q7,
        din1 => row_pixels_V_q7,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_7_fu_908_p4);

    mux_21_8_1_1_U232 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q6,
        din1 => row_pixels_V_1_q6,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_8_fu_918_p4);

    mux_21_8_1_1_U233 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q5,
        din1 => row_pixels_V_q5,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_9_fu_928_p4);

    mux_21_8_1_1_U234 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q4,
        din1 => row_pixels_V_1_q4,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_10_fu_964_p4);

    mux_21_8_1_1_U235 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q3,
        din1 => row_pixels_V_q3,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_11_fu_974_p4);

    mux_21_8_1_1_U236 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q2,
        din1 => row_pixels_V_1_q2,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_12_fu_984_p4);

    mux_21_8_1_1_U237 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_1_q1,
        din1 => row_pixels_V_q1,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_13_fu_994_p4);

    mux_21_8_1_1_U238 : component accelerator_v2_mux_21_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 1,
        dout_WIDTH => 8)
    port map (
        din0 => row_pixels_V_q0,
        din1 => row_pixels_V_1_q0,
        din2 => trunc_ln223_fu_835_p1,
        dout => gray_V_14_fu_1004_p4);

    flow_control_loop_pipe_sequential_init_U : component accelerator_v2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ob_1_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln211_fu_535_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ob_1_fu_120 <= ob_2_fu_541_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ob_1_fu_120 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ob_reg_1113 <= ap_sig_allocacmp_ob;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln223_10_fu_745_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_6));
    add_ln223_11_fu_757_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_D));
    add_ln223_12_fu_779_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_7));
    add_ln223_13_fu_791_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_F));
    add_ln223_14_fu_813_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_8));
    add_ln223_1_fu_587_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_3));
    add_ln223_2_fu_609_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_2));
    add_ln223_3_fu_621_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_5));
    add_ln223_4_fu_643_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_3));
    add_ln223_5_fu_655_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_7));
    add_ln223_6_fu_677_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_4));
    add_ln223_7_fu_689_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_9));
    add_ln223_8_fu_711_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_5));
    add_ln223_9_fu_723_p2 <= std_logic_vector(unsigned(empty_fu_559_p2) + unsigned(ap_const_lv10_B));
    add_ln223_fu_575_p2 <= std_logic_vector(unsigned(trunc_ln223_1_fu_565_p4) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_01001 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln211_fu_535_p2)
    begin
        if (((icmp_ln211_fu_535_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ob_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ob_1_fu_120, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ob <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_ob <= ob_1_fu_120;
        end if; 
    end process;

    empty_fu_559_p2 <= std_logic_vector(unsigned(p_shl_fu_551_p3) - unsigned(zext_ln211_fu_547_p1));
    icmp_ln211_fu_535_p2 <= "1" when (ap_sig_allocacmp_ob = ap_const_lv6_2B) else "0";
    icmp_ln218_fu_830_p2 <= "1" when (unsigned(ob_reg_1113) < unsigned(ap_const_lv6_2A)) else "0";
    icmp_ln231_fu_1074_p2 <= "1" when (ob_reg_1113 = ap_const_lv6_2A) else "0";
    icmp_ln232_fu_1085_p2 <= "1" when (ob_reg_1113 = ap_const_lv6_0) else "0";
    lshr_ln223_1_fu_593_p4 <= add_ln223_1_fu_587_p2(9 downto 1);
    lshr_ln223_2_fu_627_p4 <= add_ln223_3_fu_621_p2(9 downto 1);
    lshr_ln223_3_fu_661_p4 <= add_ln223_5_fu_655_p2(9 downto 1);
    lshr_ln223_4_fu_695_p4 <= add_ln223_7_fu_689_p2(9 downto 1);
    lshr_ln223_5_fu_729_p4 <= add_ln223_9_fu_723_p2(9 downto 1);
    lshr_ln223_6_fu_763_p4 <= add_ln223_11_fu_757_p2(9 downto 1);
    lshr_ln223_7_fu_797_p4 <= add_ln223_13_fu_791_p2(9 downto 1);
    ob_2_fu_541_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ob) + unsigned(ap_const_lv6_1));
    out_burst_data_V_1_fu_1050_p3 <= 
        p_Result_1_fu_1014_p17 when (icmp_ln218_fu_830_p2(0) = '1') else 
        p_Result_s_fu_938_p12;
    out_stream_TDATA <= (out_burst_data_V_1_fu_1050_p3(127 downto 8) & zext_ln214_fu_1058_p1);

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDEST <= ap_const_lv1_0;
    out_stream_TID <= ap_const_lv1_0;
    out_stream_TKEEP <= ap_const_lv16_FFFF;
    out_stream_TLAST <= (icmp_ln231_fu_1074_p2 and cmp39);
    out_stream_TSTRB <= ap_const_lv16_FFFF;
    out_stream_TUSER <= (icmp_ln232_fu_1085_p2 and cmp43);

    out_stream_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_1014_p17 <= (((((((((((((((gray_V_fu_838_p4 & gray_V_1_fu_848_p4) & gray_V_2_fu_858_p4) & gray_V_3_fu_868_p4) & gray_V_4_fu_878_p4) & gray_V_5_fu_888_p4) & gray_V_6_fu_898_p4) & gray_V_7_fu_908_p4) & gray_V_8_fu_918_p4) & gray_V_9_fu_928_p4) & gray_V_10_fu_964_p4) & gray_V_11_fu_974_p4) & gray_V_12_fu_984_p4) & gray_V_13_fu_994_p4) & gray_V_14_fu_1004_p4) & ap_const_lv8_0);
    p_Result_s_fu_938_p12 <= ((((((((((gray_V_fu_838_p4 & gray_V_1_fu_848_p4) & gray_V_2_fu_858_p4) & gray_V_3_fu_868_p4) & gray_V_4_fu_878_p4) & gray_V_5_fu_888_p4) & gray_V_6_fu_898_p4) & gray_V_7_fu_908_p4) & gray_V_8_fu_918_p4) & gray_V_9_fu_928_p4) & ap_const_lv48_0);
    p_shl_fu_551_p3 <= (ap_sig_allocacmp_ob & ap_const_lv4_0);
    row_pixels_V_1_address0 <= zext_ln223_14_fu_819_p1(9 - 1 downto 0);
    row_pixels_V_1_address1 <= zext_ln223_13_fu_807_p1(9 - 1 downto 0);
    row_pixels_V_1_address10 <= zext_ln223_4_fu_649_p1(9 - 1 downto 0);
    row_pixels_V_1_address11 <= zext_ln223_3_fu_637_p1(9 - 1 downto 0);
    row_pixels_V_1_address12 <= zext_ln223_2_fu_615_p1(9 - 1 downto 0);
    row_pixels_V_1_address13 <= zext_ln223_1_fu_603_p1(9 - 1 downto 0);
    row_pixels_V_1_address14 <= zext_ln223_fu_581_p1(9 - 1 downto 0);
    row_pixels_V_1_address2 <= zext_ln223_12_fu_785_p1(9 - 1 downto 0);
    row_pixels_V_1_address3 <= zext_ln223_11_fu_773_p1(9 - 1 downto 0);
    row_pixels_V_1_address4 <= zext_ln223_10_fu_751_p1(9 - 1 downto 0);
    row_pixels_V_1_address5 <= zext_ln223_9_fu_739_p1(9 - 1 downto 0);
    row_pixels_V_1_address6 <= zext_ln223_8_fu_717_p1(9 - 1 downto 0);
    row_pixels_V_1_address7 <= zext_ln223_7_fu_705_p1(9 - 1 downto 0);
    row_pixels_V_1_address8 <= zext_ln223_6_fu_683_p1(9 - 1 downto 0);
    row_pixels_V_1_address9 <= zext_ln223_5_fu_671_p1(9 - 1 downto 0);

    row_pixels_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce0 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce1 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce10 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce10 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce11 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce11 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce12_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce12 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce12 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce13_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce13 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce13 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce14_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce14 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce14 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce2 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce3 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce4 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce5 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce6 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce7 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce8 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_1_ce9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_1_ce9 <= ap_const_logic_1;
        else 
            row_pixels_V_1_ce9 <= ap_const_logic_0;
        end if; 
    end process;

    row_pixels_V_address0 <= zext_ln223_14_fu_819_p1(9 - 1 downto 0);
    row_pixels_V_address1 <= zext_ln223_13_fu_807_p1(9 - 1 downto 0);
    row_pixels_V_address10 <= zext_ln223_4_fu_649_p1(9 - 1 downto 0);
    row_pixels_V_address11 <= zext_ln223_3_fu_637_p1(9 - 1 downto 0);
    row_pixels_V_address12 <= zext_ln223_2_fu_615_p1(9 - 1 downto 0);
    row_pixels_V_address13 <= zext_ln223_1_fu_603_p1(9 - 1 downto 0);
    row_pixels_V_address14 <= zext_ln223_fu_581_p1(9 - 1 downto 0);
    row_pixels_V_address2 <= zext_ln223_12_fu_785_p1(9 - 1 downto 0);
    row_pixels_V_address3 <= zext_ln223_11_fu_773_p1(9 - 1 downto 0);
    row_pixels_V_address4 <= zext_ln223_10_fu_751_p1(9 - 1 downto 0);
    row_pixels_V_address5 <= zext_ln223_9_fu_739_p1(9 - 1 downto 0);
    row_pixels_V_address6 <= zext_ln223_8_fu_717_p1(9 - 1 downto 0);
    row_pixels_V_address7 <= zext_ln223_7_fu_705_p1(9 - 1 downto 0);
    row_pixels_V_address8 <= zext_ln223_6_fu_683_p1(9 - 1 downto 0);
    row_pixels_V_address9 <= zext_ln223_5_fu_671_p1(9 - 1 downto 0);

    row_pixels_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce0 <= ap_const_logic_1;
        else 
            row_pixels_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce1 <= ap_const_logic_1;
        else 
            row_pixels_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce10 <= ap_const_logic_1;
        else 
            row_pixels_V_ce10 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce11 <= ap_const_logic_1;
        else 
            row_pixels_V_ce11 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce12_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce12 <= ap_const_logic_1;
        else 
            row_pixels_V_ce12 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce13_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce13 <= ap_const_logic_1;
        else 
            row_pixels_V_ce13 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce14_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce14 <= ap_const_logic_1;
        else 
            row_pixels_V_ce14 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce2 <= ap_const_logic_1;
        else 
            row_pixels_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce3 <= ap_const_logic_1;
        else 
            row_pixels_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce4 <= ap_const_logic_1;
        else 
            row_pixels_V_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce5 <= ap_const_logic_1;
        else 
            row_pixels_V_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce6 <= ap_const_logic_1;
        else 
            row_pixels_V_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce7 <= ap_const_logic_1;
        else 
            row_pixels_V_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce8 <= ap_const_logic_1;
        else 
            row_pixels_V_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    row_pixels_V_ce9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            row_pixels_V_ce9 <= ap_const_logic_1;
        else 
            row_pixels_V_ce9 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln223_1_fu_565_p4 <= empty_fu_559_p2(9 downto 1);
    trunc_ln223_fu_835_p1 <= ob_reg_1113(1 - 1 downto 0);
    zext_ln211_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_ob),10));
    zext_ln214_fu_1058_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ob_reg_1113),8));
    zext_ln223_10_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_10_fu_745_p2),64));
    zext_ln223_11_fu_773_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_6_fu_763_p4),64));
    zext_ln223_12_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_12_fu_779_p2),64));
    zext_ln223_13_fu_807_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_7_fu_797_p4),64));
    zext_ln223_14_fu_819_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_14_fu_813_p2),64));
    zext_ln223_1_fu_603_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_1_fu_593_p4),64));
    zext_ln223_2_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_2_fu_609_p2),64));
    zext_ln223_3_fu_637_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_2_fu_627_p4),64));
    zext_ln223_4_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_4_fu_643_p2),64));
    zext_ln223_5_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_3_fu_661_p4),64));
    zext_ln223_6_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_6_fu_677_p2),64));
    zext_ln223_7_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_4_fu_695_p4),64));
    zext_ln223_8_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_8_fu_711_p2),64));
    zext_ln223_9_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln223_5_fu_729_p4),64));
    zext_ln223_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_fu_575_p2),64));
end behav;
