-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accelerator_v2 is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_breath : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_breath : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC );
end;


architecture behav of accelerator_v2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "accelerator_v2_accelerator_v2,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.886313,HLS_SYN_LAT=922081,HLS_SYN_TPT=922082,HLS_SYN_MEM=51,HLS_SYN_DSP=0,HLS_SYN_FF=4614,HLS_SYN_LUT=7411,HLS_VERSION=2022_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal unpack_U0_ap_start : STD_LOGIC;
    signal unpack_U0_ap_done : STD_LOGIC;
    signal unpack_U0_ap_continue : STD_LOGIC;
    signal unpack_U0_ap_idle : STD_LOGIC;
    signal unpack_U0_ap_ready : STD_LOGIC;
    signal unpack_U0_start_out : STD_LOGIC;
    signal unpack_U0_start_write : STD_LOGIC;
    signal unpack_U0_in_stream_TREADY : STD_LOGIC;
    signal unpack_U0_bgr_stream1_din : STD_LOGIC_VECTOR (23 downto 0);
    signal unpack_U0_bgr_stream1_write : STD_LOGIC;
    signal unpack_U0_in_breath : STD_LOGIC_VECTOR (0 downto 0);
    signal unpack_U0_in_breath_ap_vld : STD_LOGIC;
    signal pad_U0_ap_start : STD_LOGIC;
    signal pad_U0_ap_done : STD_LOGIC;
    signal pad_U0_ap_continue : STD_LOGIC;
    signal pad_U0_ap_idle : STD_LOGIC;
    signal pad_U0_ap_ready : STD_LOGIC;
    signal pad_U0_start_out : STD_LOGIC;
    signal pad_U0_start_write : STD_LOGIC;
    signal pad_U0_bgr_stream1_read : STD_LOGIC;
    signal pad_U0_padded_stream2_din : STD_LOGIC_VECTOR (23 downto 0);
    signal pad_U0_padded_stream2_write : STD_LOGIC;
    signal process_pixels_U0_ap_start : STD_LOGIC;
    signal process_pixels_U0_start_out : STD_LOGIC;
    signal process_pixels_U0_start_write : STD_LOGIC;
    signal process_pixels_U0_padded_stream2_read : STD_LOGIC;
    signal process_pixels_U0_gray_stream3_din : STD_LOGIC_VECTOR (7 downto 0);
    signal process_pixels_U0_gray_stream3_write : STD_LOGIC;
    signal process_pixels_U0_ap_done : STD_LOGIC;
    signal process_pixels_U0_ap_ready : STD_LOGIC;
    signal process_pixels_U0_ap_idle : STD_LOGIC;
    signal process_pixels_U0_ap_continue : STD_LOGIC;
    signal repack_U0_ap_start : STD_LOGIC;
    signal repack_U0_ap_done : STD_LOGIC;
    signal repack_U0_ap_continue : STD_LOGIC;
    signal repack_U0_ap_idle : STD_LOGIC;
    signal repack_U0_ap_ready : STD_LOGIC;
    signal repack_U0_gray_stream3_read : STD_LOGIC;
    signal repack_U0_out_stream_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal repack_U0_out_stream_TVALID : STD_LOGIC;
    signal repack_U0_out_stream_TKEEP : STD_LOGIC_VECTOR (15 downto 0);
    signal repack_U0_out_stream_TSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal repack_U0_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal repack_U0_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal repack_U0_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal repack_U0_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal repack_U0_out_breath : STD_LOGIC_VECTOR (0 downto 0);
    signal repack_U0_out_breath_ap_vld : STD_LOGIC;
    signal bgr_stream_full_n : STD_LOGIC;
    signal bgr_stream_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal bgr_stream_num_data_valid : STD_LOGIC_VECTOR (12 downto 0);
    signal bgr_stream_fifo_cap : STD_LOGIC_VECTOR (12 downto 0);
    signal bgr_stream_empty_n : STD_LOGIC;
    signal padded_stream_full_n : STD_LOGIC;
    signal padded_stream_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal padded_stream_num_data_valid : STD_LOGIC_VECTOR (12 downto 0);
    signal padded_stream_fifo_cap : STD_LOGIC_VECTOR (12 downto 0);
    signal padded_stream_empty_n : STD_LOGIC;
    signal gray_stream_full_n : STD_LOGIC;
    signal gray_stream_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_stream_num_data_valid : STD_LOGIC_VECTOR (12 downto 0);
    signal gray_stream_fifo_cap : STD_LOGIC_VECTOR (12 downto 0);
    signal gray_stream_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal start_for_pad_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pad_U0_full_n : STD_LOGIC;
    signal start_for_pad_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pad_U0_empty_n : STD_LOGIC;
    signal start_for_process_pixels_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_process_pixels_U0_full_n : STD_LOGIC;
    signal start_for_process_pixels_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_process_pixels_U0_empty_n : STD_LOGIC;
    signal start_for_repack_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_repack_U0_full_n : STD_LOGIC;
    signal start_for_repack_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_repack_U0_empty_n : STD_LOGIC;

    component accelerator_v2_unpack IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        bgr_stream1_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bgr_stream1_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        bgr_stream1_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        bgr_stream1_full_n : IN STD_LOGIC;
        bgr_stream1_write : OUT STD_LOGIC;
        in_breath : OUT STD_LOGIC_VECTOR (0 downto 0);
        in_breath_ap_vld : OUT STD_LOGIC );
    end component;


    component accelerator_v2_pad IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        bgr_stream1_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        bgr_stream1_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        bgr_stream1_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        bgr_stream1_empty_n : IN STD_LOGIC;
        bgr_stream1_read : OUT STD_LOGIC;
        padded_stream2_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        padded_stream2_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        padded_stream2_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        padded_stream2_full_n : IN STD_LOGIC;
        padded_stream2_write : OUT STD_LOGIC );
    end component;


    component accelerator_v2_process_pixels IS
    port (
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        padded_stream2_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        padded_stream2_empty_n : IN STD_LOGIC;
        padded_stream2_read : OUT STD_LOGIC;
        gray_stream3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        gray_stream3_full_n : IN STD_LOGIC;
        gray_stream3_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component accelerator_v2_repack IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        gray_stream3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        gray_stream3_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        gray_stream3_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        gray_stream3_empty_n : IN STD_LOGIC;
        gray_stream3_read : OUT STD_LOGIC;
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_breath : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_breath_ap_vld : OUT STD_LOGIC );
    end component;


    component accelerator_v2_fifo_w24_d2560_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component accelerator_v2_fifo_w24_d2576_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component accelerator_v2_fifo_w8_d3864_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component accelerator_v2_start_for_pad_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component accelerator_v2_start_for_process_pixels_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component accelerator_v2_start_for_repack_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component accelerator_v2_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component accelerator_v2_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    unpack_U0 : component accelerator_v2_unpack
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => unpack_U0_ap_start,
        start_full_n => start_for_pad_U0_full_n,
        ap_done => unpack_U0_ap_done,
        ap_continue => unpack_U0_ap_continue,
        ap_idle => unpack_U0_ap_idle,
        ap_ready => unpack_U0_ap_ready,
        start_out => unpack_U0_start_out,
        start_write => unpack_U0_start_write,
        in_stream_TDATA => in_stream_TDATA,
        in_stream_TVALID => in_stream_TVALID,
        in_stream_TREADY => unpack_U0_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP,
        in_stream_TSTRB => in_stream_TSTRB,
        in_stream_TUSER => in_stream_TUSER,
        in_stream_TLAST => in_stream_TLAST,
        in_stream_TID => in_stream_TID,
        in_stream_TDEST => in_stream_TDEST,
        bgr_stream1_din => unpack_U0_bgr_stream1_din,
        bgr_stream1_num_data_valid => bgr_stream_num_data_valid,
        bgr_stream1_fifo_cap => bgr_stream_fifo_cap,
        bgr_stream1_full_n => bgr_stream_full_n,
        bgr_stream1_write => unpack_U0_bgr_stream1_write,
        in_breath => unpack_U0_in_breath,
        in_breath_ap_vld => unpack_U0_in_breath_ap_vld);

    pad_U0 : component accelerator_v2_pad
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pad_U0_ap_start,
        start_full_n => start_for_process_pixels_U0_full_n,
        ap_done => pad_U0_ap_done,
        ap_continue => pad_U0_ap_continue,
        ap_idle => pad_U0_ap_idle,
        ap_ready => pad_U0_ap_ready,
        start_out => pad_U0_start_out,
        start_write => pad_U0_start_write,
        bgr_stream1_dout => bgr_stream_dout,
        bgr_stream1_num_data_valid => bgr_stream_num_data_valid,
        bgr_stream1_fifo_cap => bgr_stream_fifo_cap,
        bgr_stream1_empty_n => bgr_stream_empty_n,
        bgr_stream1_read => pad_U0_bgr_stream1_read,
        padded_stream2_din => pad_U0_padded_stream2_din,
        padded_stream2_num_data_valid => padded_stream_num_data_valid,
        padded_stream2_fifo_cap => padded_stream_fifo_cap,
        padded_stream2_full_n => padded_stream_full_n,
        padded_stream2_write => pad_U0_padded_stream2_write);

    process_pixels_U0 : component accelerator_v2_process_pixels
    port map (
        ap_start => process_pixels_U0_ap_start,
        start_full_n => start_for_repack_U0_full_n,
        start_out => process_pixels_U0_start_out,
        start_write => process_pixels_U0_start_write,
        padded_stream2_dout => padded_stream_dout,
        padded_stream2_empty_n => padded_stream_empty_n,
        padded_stream2_read => process_pixels_U0_padded_stream2_read,
        gray_stream3_din => process_pixels_U0_gray_stream3_din,
        gray_stream3_full_n => gray_stream_full_n,
        gray_stream3_write => process_pixels_U0_gray_stream3_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_done => process_pixels_U0_ap_done,
        ap_ready => process_pixels_U0_ap_ready,
        ap_idle => process_pixels_U0_ap_idle,
        ap_continue => process_pixels_U0_ap_continue);

    repack_U0 : component accelerator_v2_repack
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => repack_U0_ap_start,
        ap_done => repack_U0_ap_done,
        ap_continue => repack_U0_ap_continue,
        ap_idle => repack_U0_ap_idle,
        ap_ready => repack_U0_ap_ready,
        gray_stream3_dout => gray_stream_dout,
        gray_stream3_num_data_valid => gray_stream_num_data_valid,
        gray_stream3_fifo_cap => gray_stream_fifo_cap,
        gray_stream3_empty_n => gray_stream_empty_n,
        gray_stream3_read => repack_U0_gray_stream3_read,
        out_stream_TDATA => repack_U0_out_stream_TDATA,
        out_stream_TVALID => repack_U0_out_stream_TVALID,
        out_stream_TREADY => out_stream_TREADY,
        out_stream_TKEEP => repack_U0_out_stream_TKEEP,
        out_stream_TSTRB => repack_U0_out_stream_TSTRB,
        out_stream_TUSER => repack_U0_out_stream_TUSER,
        out_stream_TLAST => repack_U0_out_stream_TLAST,
        out_stream_TID => repack_U0_out_stream_TID,
        out_stream_TDEST => repack_U0_out_stream_TDEST,
        out_breath => repack_U0_out_breath,
        out_breath_ap_vld => repack_U0_out_breath_ap_vld);

    bgr_stream_U : component accelerator_v2_fifo_w24_d2560_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => unpack_U0_bgr_stream1_din,
        if_full_n => bgr_stream_full_n,
        if_write => unpack_U0_bgr_stream1_write,
        if_dout => bgr_stream_dout,
        if_num_data_valid => bgr_stream_num_data_valid,
        if_fifo_cap => bgr_stream_fifo_cap,
        if_empty_n => bgr_stream_empty_n,
        if_read => pad_U0_bgr_stream1_read);

    padded_stream_U : component accelerator_v2_fifo_w24_d2576_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pad_U0_padded_stream2_din,
        if_full_n => padded_stream_full_n,
        if_write => pad_U0_padded_stream2_write,
        if_dout => padded_stream_dout,
        if_num_data_valid => padded_stream_num_data_valid,
        if_fifo_cap => padded_stream_fifo_cap,
        if_empty_n => padded_stream_empty_n,
        if_read => process_pixels_U0_padded_stream2_read);

    gray_stream_U : component accelerator_v2_fifo_w8_d3864_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => process_pixels_U0_gray_stream3_din,
        if_full_n => gray_stream_full_n,
        if_write => process_pixels_U0_gray_stream3_write,
        if_dout => gray_stream_dout,
        if_num_data_valid => gray_stream_num_data_valid,
        if_fifo_cap => gray_stream_fifo_cap,
        if_empty_n => gray_stream_empty_n,
        if_read => repack_U0_gray_stream3_read);

    start_for_pad_U0_U : component accelerator_v2_start_for_pad_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pad_U0_din,
        if_full_n => start_for_pad_U0_full_n,
        if_write => unpack_U0_start_write,
        if_dout => start_for_pad_U0_dout,
        if_empty_n => start_for_pad_U0_empty_n,
        if_read => pad_U0_ap_ready);

    start_for_process_pixels_U0_U : component accelerator_v2_start_for_process_pixels_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_process_pixels_U0_din,
        if_full_n => start_for_process_pixels_U0_full_n,
        if_write => pad_U0_start_write,
        if_dout => start_for_process_pixels_U0_dout,
        if_empty_n => start_for_process_pixels_U0_empty_n,
        if_read => process_pixels_U0_ap_ready);

    start_for_repack_U0_U : component accelerator_v2_start_for_repack_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_repack_U0_din,
        if_full_n => start_for_repack_U0_full_n,
        if_write => process_pixels_U0_start_write,
        if_dout => start_for_repack_U0_dout,
        if_empty_n => start_for_repack_U0_empty_n,
        if_read => repack_U0_ap_ready);




    ap_done <= ap_sync_done;
    ap_idle <= (unpack_U0_ap_idle and repack_U0_ap_idle and process_pixels_U0_ap_idle and pad_U0_ap_idle);
    ap_ready <= unpack_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_done <= (unpack_U0_ap_done and repack_U0_ap_done);
    in_breath <= unpack_U0_in_breath;
    in_stream_TREADY <= unpack_U0_in_stream_TREADY;
    out_breath <= repack_U0_out_breath;
    out_stream_TDATA <= repack_U0_out_stream_TDATA;
    out_stream_TDEST <= repack_U0_out_stream_TDEST;
    out_stream_TID <= repack_U0_out_stream_TID;
    out_stream_TKEEP <= repack_U0_out_stream_TKEEP;
    out_stream_TLAST <= repack_U0_out_stream_TLAST;
    out_stream_TSTRB <= repack_U0_out_stream_TSTRB;
    out_stream_TUSER <= repack_U0_out_stream_TUSER;
    out_stream_TVALID <= repack_U0_out_stream_TVALID;
    pad_U0_ap_continue <= ap_const_logic_1;
    pad_U0_ap_start <= start_for_pad_U0_empty_n;
    process_pixels_U0_ap_continue <= ap_const_logic_1;
    process_pixels_U0_ap_start <= start_for_process_pixels_U0_empty_n;
    repack_U0_ap_continue <= ap_sync_done;
    repack_U0_ap_start <= start_for_repack_U0_empty_n;
    start_for_pad_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_process_pixels_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_repack_U0_din <= (0=>ap_const_logic_1, others=>'-');
    unpack_U0_ap_continue <= ap_sync_done;
    unpack_U0_ap_start <= ap_start;
end behav;
