-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_passthrough_xfMat2axiStrm_32_0_460_640_4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    img_blur_data49_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_blur_data49_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_blur_data49_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_blur_data49_empty_n : IN STD_LOGIC;
    img_blur_data49_read : OUT STD_LOGIC;
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC;
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of image_passthrough_xfMat2axiStrm_32_0_460_640_4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_img_blur_data49_read : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TREADY : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_idle : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_continue : STD_LOGIC;
    signal grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call5 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready : STD_LOGIC;
    signal ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done : STD_LOGIC := '0';
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal regslice_both_stream_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal stream_out_TVALID_int_regslice : STD_LOGIC;
    signal stream_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_stream_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component image_passthrough_xfMat2axiStrm_32_0_460_640_4_1 IS
    port (
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        img_blur_data49_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_blur_data49_empty_n : IN STD_LOGIC;
        img_blur_data49_read : OUT STD_LOGIC;
        stream_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        stream_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        stream_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        p_read_ap_vld : IN STD_LOGIC;
        p_read1_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        stream_out_TVALID : OUT STD_LOGIC;
        stream_out_TREADY : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component image_passthrough_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52 : component image_passthrough_xfMat2axiStrm_32_0_460_640_4_1
    port map (
        p_read => p_read,
        p_read1 => p_read1,
        img_blur_data49_dout => img_blur_data49_dout,
        img_blur_data49_empty_n => img_blur_data49_empty_n,
        img_blur_data49_read => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_img_blur_data49_read,
        stream_out_TDATA => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TDATA,
        stream_out_TKEEP => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TKEEP,
        stream_out_TSTRB => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TSTRB,
        stream_out_TLAST => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TLAST,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        p_read_ap_vld => ap_const_logic_1,
        p_read1_ap_vld => ap_const_logic_1,
        ap_start => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start,
        stream_out_TVALID => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID,
        stream_out_TREADY => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TREADY,
        ap_done => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done,
        ap_ready => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready,
        ap_idle => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_idle,
        ap_continue => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_continue);

    regslice_both_stream_out_V_data_V_U : component image_passthrough_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TDATA,
        vld_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID,
        ack_in => stream_out_TREADY_int_regslice,
        data_out => stream_out_TDATA,
        vld_out => regslice_both_stream_out_V_data_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_data_V_U_apdone_blk);

    regslice_both_stream_out_V_keep_V_U : component image_passthrough_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TKEEP,
        vld_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_keep_V_U_ack_in_dummy,
        data_out => stream_out_TKEEP,
        vld_out => regslice_both_stream_out_V_keep_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_keep_V_U_apdone_blk);

    regslice_both_stream_out_V_strb_V_U : component image_passthrough_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TSTRB,
        vld_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_strb_V_U_ack_in_dummy,
        data_out => stream_out_TSTRB,
        vld_out => regslice_both_stream_out_V_strb_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_strb_V_U_apdone_blk);

    regslice_both_stream_out_V_last_V_U : component image_passthrough_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TLAST,
        vld_in => grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID,
        ack_in => regslice_both_stream_out_V_last_V_U_ack_in_dummy,
        data_out => stream_out_TLAST,
        vld_out => regslice_both_stream_out_V_last_V_U_vld_out,
        ack_out => stream_out_TREADY,
        apdone_blk => regslice_both_stream_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done <= ap_const_logic_0;
                elsif ((grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready <= ap_const_logic_0;
                elsif ((grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready = ap_const_logic_1)) then 
                    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, ap_CS_fsm_state3, regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call5_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call5 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready, ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready and ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, regslice_both_stream_out_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done <= (grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done or ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_done);
    ap_sync_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready <= (grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready or ap_sync_reg_grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_ready);

    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_continue_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_continue <= ap_const_logic_1;
        else 
            grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start <= grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_ap_start_reg;
    grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TREADY <= (stream_out_TREADY_int_regslice and ap_CS_fsm_state2);

    img_blur_data49_read_assign_proc : process(grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_img_blur_data49_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            img_blur_data49_read <= grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_img_blur_data49_read;
        else 
            img_blur_data49_read <= ap_const_logic_0;
        end if; 
    end process;

    stream_out_TVALID <= regslice_both_stream_out_V_data_V_U_vld_out;
    stream_out_TVALID_int_regslice <= grp_xfMat2axiStrm_32_0_460_640_4_1_fu_52_stream_out_TVALID;
end behav;
