-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    img_gray_data48_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_gray_data48_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_gray_data48_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_gray_data48_empty_n : IN STD_LOGIC;
    img_gray_data48_read : OUT STD_LOGIC;
    img_blur_data49_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    img_blur_data49_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_blur_data49_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_blur_data49_full_n : IN STD_LOGIC;
    img_blur_data49_write : OUT STD_LOGIC );
end;


architecture behav of image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (14 downto 0) := "000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (14 downto 0) := "000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (14 downto 0) := "000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (14 downto 0) := "000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (14 downto 0) := "000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (14 downto 0) := "000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (14 downto 0) := "000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (14 downto 0) := "000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (14 downto 0) := "000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (14 downto 0) := "001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (14 downto 0) := "010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_91_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_reg_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal trunc_ln1312_fu_109_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1312_reg_157 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal trunc_ln1312_1_reg_162 : STD_LOGIC_VECTOR (15 downto 0);
    signal cf_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal cf_ce0 : STD_LOGIC;
    signal cf_we0 : STD_LOGIC;
    signal cf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_done : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_idle : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_ready : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_ce0 : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_we0 : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_sum_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_sum_1_out_ap_vld : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_opcode : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_ce : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_ce : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_done : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_idle : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_ready : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_ce0 : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_we0 : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_1_out_ap_vld : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_out_ap_vld : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_ce : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_ce : STD_LOGIC;
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start : STD_LOGIC;
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done : STD_LOGIC;
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_idle : STD_LOGIC;
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_ready : STD_LOGIC;
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_gray_data48_read : STD_LOGIC;
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_write : STD_LOGIC;
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call8 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_167_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_167_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_167_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_167_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_167_ce : STD_LOGIC;
    signal grp_fu_171_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_171_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_171_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_171_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        cf_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        cf_ce0 : OUT STD_LOGIC;
        cf_we0 : OUT STD_LOGIC;
        cf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_1_out_ap_vld : OUT STD_LOGIC;
        grp_fu_167_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_167_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_167_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_167_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_167_p_ce : OUT STD_LOGIC;
        grp_fu_171_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_171_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_171_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_171_p_ce : OUT STD_LOGIC );
    end component;


    component image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        cf_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        cf_ce0 : OUT STD_LOGIC;
        cf_we0 : OUT STD_LOGIC;
        cf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        cf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        sum : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        weights_1_out_ap_vld : OUT STD_LOGIC;
        weights_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        weights_out_ap_vld : OUT STD_LOGIC;
        grp_fu_167_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_167_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_167_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_167_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_167_p_ce : OUT STD_LOGIC;
        grp_fu_171_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_171_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_171_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_171_p_ce : OUT STD_LOGIC );
    end component;


    component image_passthrough_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_gray_data48_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_gray_data48_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_gray_data48_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_gray_data48_empty_n : IN STD_LOGIC;
        img_gray_data48_read : OUT STD_LOGIC;
        img_blur_data49_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_blur_data49_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_blur_data49_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_blur_data49_full_n : IN STD_LOGIC;
        img_blur_data49_write : OUT STD_LOGIC;
        img_height : IN STD_LOGIC_VECTOR (15 downto 0);
        img_width : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component image_passthrough_fdiv_32ns_32ns_32_10_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component image_passthrough_faddfsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component image_passthrough_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_s_cf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    cf_U : component image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_s_cf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => cf_address0,
        ce0 => cf_ce0,
        we0 => cf_we0,
        d0 => cf_d0,
        q0 => cf_q0);

    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64 : component image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start,
        ap_done => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_done,
        ap_idle => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_idle,
        ap_ready => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_ready,
        cf_address0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_address0,
        cf_ce0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_ce0,
        cf_we0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_we0,
        cf_d0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_d0,
        sum_1_out => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_sum_1_out,
        sum_1_out_ap_vld => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_sum_1_out_ap_vld,
        grp_fu_167_p_din0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din0,
        grp_fu_167_p_din1 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din1,
        grp_fu_167_p_opcode => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_opcode,
        grp_fu_167_p_dout0 => grp_fu_167_p2,
        grp_fu_167_p_ce => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_ce,
        grp_fu_171_p_din0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din0,
        grp_fu_171_p_din1 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din1,
        grp_fu_171_p_dout0 => grp_fu_171_p2,
        grp_fu_171_p_ce => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_ce);

    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71 : component image_passthrough_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start,
        ap_done => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_done,
        ap_idle => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_idle,
        ap_ready => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_ready,
        cf_address0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_address0,
        cf_ce0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_ce0,
        cf_we0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_we0,
        cf_d0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_d0,
        cf_q0 => cf_q0,
        sum => sum_reg_146,
        weights_1_out => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_1_out,
        weights_1_out_ap_vld => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_1_out_ap_vld,
        weights_out => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_out,
        weights_out_ap_vld => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_out_ap_vld,
        grp_fu_167_p_din0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din0,
        grp_fu_167_p_din1 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din1,
        grp_fu_167_p_opcode => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_opcode,
        grp_fu_167_p_dout0 => grp_fu_167_p2,
        grp_fu_167_p_ce => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_ce,
        grp_fu_171_p_din0 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din0,
        grp_fu_171_p_din1 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din1,
        grp_fu_171_p_dout0 => grp_fu_171_p2,
        grp_fu_171_p_ce => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_ce);

    grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79 : component image_passthrough_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start,
        ap_done => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done,
        ap_idle => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_idle,
        ap_ready => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_ready,
        img_gray_data48_dout => img_gray_data48_dout,
        img_gray_data48_num_data_valid => ap_const_lv2_0,
        img_gray_data48_fifo_cap => ap_const_lv2_0,
        img_gray_data48_empty_n => img_gray_data48_empty_n,
        img_gray_data48_read => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_gray_data48_read,
        img_blur_data49_din => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_din,
        img_blur_data49_num_data_valid => ap_const_lv2_0,
        img_blur_data49_fifo_cap => ap_const_lv2_0,
        img_blur_data49_full_n => img_blur_data49_full_n,
        img_blur_data49_write => grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_write,
        img_height => trunc_ln1312_reg_157,
        img_width => trunc_ln1312_1_reg_162,
        p_read => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_1_out,
        p_read1 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_weights_out);

    fdiv_32ns_32ns_32_10_no_dsp_1_U156 : component image_passthrough_fdiv_32ns_32ns_32_10_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_3F800000,
        din1 => grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_sum_1_out,
        ce => ap_const_logic_1,
        dout => grp_fu_91_p2);

    faddfsub_32ns_32ns_32_5_full_dsp_1_U157 : component image_passthrough_faddfsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_167_p0,
        din1 => grp_fu_167_p1,
        opcode => grp_fu_167_opcode,
        ce => grp_fu_167_ce,
        dout => grp_fu_167_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U158 : component image_passthrough_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_171_p0,
        din1 => grp_fu_171_p1,
        ce => grp_fu_171_ce,
        dout => grp_fu_171_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_ready = ap_const_logic_1)) then 
                    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_ready = ap_const_logic_1)) then 
                    grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                sum_reg_146 <= grp_fu_91_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                trunc_ln1312_1_reg_162 <= p_read1(17 downto 2);
                trunc_ln1312_reg_157 <= trunc_ln1312_fu_109_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_done, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_done, grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state13, ap_CS_fsm_state15)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_done)
    begin
        if ((grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state15_blk_assign_proc : process(grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done)
    begin
        if ((grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state15_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state15_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_done)
    begin
        if ((grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call8_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call8 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    cf_address0_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_address0, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_address0, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            cf_address0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            cf_address0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_address0;
        else 
            cf_address0 <= "XX";
        end if; 
    end process;


    cf_ce0_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_ce0, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_ce0, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            cf_ce0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            cf_ce0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_ce0;
        else 
            cf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    cf_d0_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_d0, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_d0, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            cf_d0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            cf_d0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_d0;
        else 
            cf_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    cf_we0_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_we0, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_we0, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            cf_we0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_cf_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            cf_we0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_cf_we0;
        else 
            cf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_ap_start_reg;
    grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_ap_start_reg;

    grp_fu_167_ce_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_ce, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_ce, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_167_ce <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_167_ce <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_ce;
        else 
            grp_fu_167_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_167_opcode_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_opcode, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_opcode, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_167_opcode <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_opcode;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_167_opcode <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_opcode),2));
        else 
            grp_fu_167_opcode <= "XX";
        end if; 
    end process;


    grp_fu_167_p0_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din0, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din0, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_167_p0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_167_p0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din0;
        else 
            grp_fu_167_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_167_p1_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din1, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din1, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_167_p1 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_167_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_167_p1 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_167_p_din1;
        else 
            grp_fu_167_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_171_ce_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_ce, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_ce, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_171_ce <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_171_ce <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_ce;
        else 
            grp_fu_171_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_171_p0_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din0, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din0, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_171_p0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_171_p0 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din0;
        else 
            grp_fu_171_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_171_p1_assign_proc : process(grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din1, grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din1, ap_CS_fsm_state2, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_171_p1 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_58_2_fu_71_grp_fu_171_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_171_p1 <= grp_GaussianBlur_3_1_0_460_640_4_2_2_Pipeline_VITIS_LOOP_48_1_fu_64_grp_fu_171_p_din1;
        else 
            grp_fu_171_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start <= grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_ap_start_reg;
    img_blur_data49_din <= grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_din;

    img_blur_data49_write_assign_proc : process(grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_write, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            img_blur_data49_write <= grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_blur_data49_write;
        else 
            img_blur_data49_write <= ap_const_logic_0;
        end if; 
    end process;


    img_gray_data48_read_assign_proc : process(grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_gray_data48_read, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            img_gray_data48_read <= grp_xfGaussianFilter3x3_0_460_640_1_0_4_2_2_12_160_s_fu_79_img_gray_data48_read;
        else 
            img_gray_data48_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln1312_fu_109_p1 <= p_read(16 - 1 downto 0);
end behav;
